### PR TITLE
Run tests on Safari

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/1034)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/1034#-L88HSv_H7eoTpjEYzOQ:-L88HSv_H7eoTpjEYzOR:b-qnkeek) (no related file):*
`testBench().resizeViewPortTo` fails for `ElementScreenCompareIT` in safari

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/1034)*

**Comment by Artur-** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/1034#-L88HSv_H7eoTpjEYzOQ:-L88wUsKuicM_dfP9TD3:b-nddd83) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

`testBench().resizeViewPortTo` fails for `ElementScreenCompareIT` in safari
</blockquote></details>

 260 tests passed (all tests)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/1034)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/1034)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/1034)*

**Pull request merged**
