### PR TITLE
Make CheckBoxElement.click() work on Firefox with Valo

### LINKED ISSUE #801: CheckBoxElement's click method throws exception with Firefox on 4.1.0.alpha1
**Originally by _christianpoitras_**

___
When calling CheckBoxElement.click() method, and exception is raised. See end of description.

My system:
Mac with OS X El Capitan 10.11.3
Firefox 44.
TestBench 4.1.0-alpha1.
selenium version 2.49.1, as version 2.47.1 does not work with Firefox on my system.
Vaadin 7.6.2

  org.openqa.selenium.WebDriverException: Element is not clickable at point (45.19999694824219, 45.19999694824219). Other element would receive the click: <label for="gwt-uid-2"></label>
  Command duration or timeout: 132 milliseconds
  Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
  System info: host: 'cou39.ircm.priv', ip: '172.16.20.166', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_45'
  Driver info: org.openqa.selenium.firefox.FirefoxDriver
  Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=44.0, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
  Session ID: 47a81ebe-bcaf-c144-a1a5-c6728c0a0b9f
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:273)
    at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
    at com.vaadin.testbench.TestBenchElement.click(TestBenchElement.java:182)
    at com.vaadin.testbench.elements.CheckBoxElement.click(CheckBoxElement.java:63)
    at com.vaadin.testbench.checkbox.integration.CheckBoxUITest.setValue(CheckBoxUITest.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

___
 Imported from https://dev.vaadin.com/ issue #19572

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #801

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/812)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/testbench/812#-KW78_jAjpewnbYvV8bw:-KW78_jAjpewnbYvV8bx:b524lfp) ([raw file](https://github.com/vaadin/testbench/blob/d67d4ab487e44491b86413fa56cf948554915a1b/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L100)):*
>  protected 
why not same visibility as isChrome?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/812)*

**Comment by Artur-** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/testbench/812#-KW78_jAjpewnbYvV8bw:-KW79boyMsTCJ9JUdY9h:b-tdwohf) ([raw file](https://github.com/vaadin/testbench/blob/d67d4ab487e44491b86413fa56cf948554915a1b/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L100)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> >  protected 
> why not same visibility as isChrome?
</details>
IMO "public" is 100% wrong for "isBrowserX" in `TestBenchElement`. Could have changed the other methods but that would potentially break something

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/812)*

**Comment by alvarezguille** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/testbench/812#-KW78_jAjpewnbYvV8bw:-KW7mkTiekaSe5du3O1k:b-euf6yc) ([raw file](https://github.com/vaadin/testbench/blob/d67d4ab487e44491b86413fa56cf948554915a1b/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L100)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> IMO "public" is 100% wrong for "isBrowserX" in `TestBenchElement`. Could have changed the other methods but that would potentially break something
</details>
Permanent solution for API will be included in 5.0 fix in #814  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/812)*

**Comment by alvarezguille** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/812#-:-KW7mvLaovI65MQ1iP_f:bnfp4nl)*

**Comment by alvarezguille** [comment]
*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/testbench/812#-KW78_jAjpewnbYvV8bw:-KW7nIAMVHkQykvptSj8:b32wtd) ([raw file](https://github.com/vaadin/testbench/blob/0346f3852078e331f3aff10fb662523715e7c735/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L100)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> Permanent solution for API will be included in 5.0 fix in #814  
</details>
ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/812)*

**Pull request merged**
