### PR TITLE
Remove Vaadin 8 and run tests with Flow

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/925)

### CODE REVIEW

**Comment by vlukashov** [comment]
Reviewed 14 of 30 files at r1, 21 of 32 files at r2.
Review status: 25 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-integration-tests/pom.xml, line 104 at r2](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwJw01B5GL4naluzcvy:-KwJw01B5GL4naluzcvz:b-qjho5h) ([raw file](https://github.com/vaadin/testbench/blob/dddc5b60764d013d80859c6ea5796f7db7df9e5f/vaadin-testbench-integration-tests/pom.xml#L104)):*
> ```XML
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>vaadin-testbench-core</artifactId>
> ```

Should this be just `vaadin-testbench`? (there is no testbench-core anymore)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by Artur-** [comment]
Review status: 25 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-integration-tests/pom.xml, line 104 at r2](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwJw01B5GL4naluzcvy:-KwJyvLZiz2HMfJBFUGV:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/dddc5b60764d013d80859c6ea5796f7db7df9e5f/vaadin-testbench-integration-tests/pom.xml#L104)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Should this be just `vaadin-testbench`? (there is no testbench-core anymore)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by vlukashov** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by vlukashov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-testbench-integration-tests/pom.xml, line 111 at r3](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwK1dV_9fucUtGkZYHc:-KwK1dV_9fucUtGkZYHd:bl93coo) ([raw file](https://github.com/vaadin/testbench/blob/c84eaaad17e2ed50c382141ad3ce4ed3eed3617d/vaadin-testbench-integration-tests/pom.xml#L111)):*
> ```XML
>     <profiles>
>         <profile>
>             <id>verify-only-phantom</id>
> ```

Let's remove this profile as well (and maybe create a local chrome profile instead).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by Artur-** [comment]
Review status: 28 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-integration-tests/pom.xml, line 111 at r3](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwK1dV_9fucUtGkZYHc:-KwKHCM_Q92VjI-Yz8sS:b-3i8wx2) ([raw file](https://github.com/vaadin/testbench/blob/c84eaaad17e2ed50c382141ad3ce4ed3eed3617d/vaadin-testbench-integration-tests/pom.xml#L111)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Let's remove this profile as well (and maybe create a local chrome profile instead).
</blockquote></details>

Changed to using Chrome and Firefox

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by vlukashov** [comment]
Review status: 28 of 29 files reviewed at latest revision, 12 unresolved discussions.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 63 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJXz6wwELGKyAaUYa:-KwKJXz6wwELGKyAaUYb:b8eah7x) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L63)):*
> ```Java
>  * using {@link #getUIClass()} or by automatically finding an enclosing UI class
>  * and based on requested features, e.g. {@link #isDebug()},
>  * {@link #isPush()}</li>
> ```

Please remove references to removed methods: `getUIClass`, `isPush`, `isDebug`.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 85 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJmm8dtOLbvQPV4hn:-KwKJmm8dtOLbvQPV4ho:b9s72ik) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L85)):*
> ```Java
>     private static final int BROWSER_TIMEOUT_IN_MS = 30 * 1000;
> 
>     private static final int BROWSER_INIT_ATTEMPTS = 5;
> ```

This field appears to be unused. Can it be removed?

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 87 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJlk_lCcQzzQEdl7b:-KwKJlk_lCcQzzQEdl7c:b9s72ik) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L87)):*
> ```Java
>     private static final int BROWSER_INIT_ATTEMPTS = 5;
> 
>     private boolean debug = false;
> ```

This field appears to be unused. Can it be removed?

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 89 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJfgLVDOc3Na7eTdk:-KwKJfgLVDOc3Na7eTdl:b9s72ik) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L89)):*
> ```Java
>     private boolean debug = false;
> 
>     private boolean push = false;
> ```

This field appears to be unused. Can it be removed?

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 110 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJsfxzOURf7zhrI2p:-KwKJsfxzOURf7zhrI2q:b99gm32) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L110)):*
> ```Java
>         if (getBooleanProperty("localPhantom")) {
>             WebDriver driver = new SetupDriver()
>                     .setupLocalDriver(Browser.PHANTOMJS);
> ```

PhantomJS?

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 119 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJqB_u8wSdhuoxvGP:-KwKJqB_u8wSdhuoxvGQ:bb6wxig) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L119)):*
> ```Java
>         int h = SCREENSHOT_HEIGHT;
> 
>         if (BrowserUtil.isIE8(getDesiredCapabilities())) {
> ```

IE8?

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 141 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJxlHgm6oW8h2rffW:-KwKJxlHgm6oW8h2rffX:b-67pwmh) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L141)):*
> ```Java
>     /**
>      * Opens the given test (defined by {@link #getTestUrl()}, optionally with
>      * debug window and/or push (depending on {@link #isDebug()} and
> ```

Please remove references to removed methods: `isDebug`.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 151 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKK7jKgkesVFyaw8O4:-KwKK7jKgkesVFyaw8O5:b-uga0gp) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L151)):*
> ```Java
>      * Opens the given test (defined by {@link #getTestUrl()}, optionally with
>      * debug window and/or push (depending on {@link #isDebug()} and
>      * {@link #isPush()}.
> ```

Please remove references to removed methods: `isPush`, `isDebug`.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 298 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKKFFM1VgYZlNqEUpy:-KwKKFFM1VgYZlNqEUpz:bk6v6mx) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L298)):*
> ```Java
>      * @return The URL path to the UI class to test
>      */
>     protected String getDeploymentPath() {
> ```

Please remove javadoc comments for removed parameters: `push`, `debug`.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 378 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKL2XHKEQwrg0aiOzS:-KwKL2XHKEQwrg0aiOzT:b-56s6re) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L378)):*
> ```Java
> 
>     // FIXME: Remove this once TB4 getRemoteControlName works properly
>     private RemoteWebDriver getRemoteDriver() {
> ```

is this FIXME still relevant?

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 400 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKL60KggnusMbvqT4Q:-KwKL60KggnusMbvqT4R:b-56s6re) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L400)):*
> ```Java
> 
>     // FIXME: Remove this once TB4 getRemoteControlName works properly
>     protected String getRemoteControlName() {
> ```

is this FIXME still relevant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by Artur-** [comment]
Review status: 28 of 29 files reviewed at latest revision, 12 unresolved discussions.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 63 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJXz6wwELGKyAaUYa:-KwKLRIjyiQYPOwMKwBK:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L63)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Please remove references to removed methods: `getUIClass`, `isPush`, `isDebug`.
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 85 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJmm8dtOLbvQPV4hn:-KwKLRcBslO2j1xKUpyY:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L85)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

This field appears to be unused. Can it be removed?
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 87 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJlk_lCcQzzQEdl7b:-KwKLS1llyCVrEr7BUGX:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L87)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

This field appears to be unused. Can it be removed?
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 89 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJfgLVDOc3Na7eTdk:-KwKLSMdTa2UKJPzXYX6:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L89)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

This field appears to be unused. Can it be removed?
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 110 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJsfxzOURf7zhrI2p:-KwKLT6XubBm7iTJ-7YU:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L110)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

PhantomJS?
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 119 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJqB_u8wSdhuoxvGP:-KwKLTeRWrpY9bqLJVKM:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L119)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

IE8?
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 141 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKJxlHgm6oW8h2rffW:-KwKLUET6fkW-T3RZgt2:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L141)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Please remove references to removed methods: `isDebug`.
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 151 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKK7jKgkesVFyaw8O4:-KwKLZrX9ZdCHtQcbylN:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L151)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Please remove references to removed methods: `isPush`, `isDebug`.
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 298 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKKFFM1VgYZlNqEUpy:-KwKLabO4IGZr9NHiz6B:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L298)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Please remove javadoc comments for removed parameters: `push`, `debug`.
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 378 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKL2XHKEQwrg0aiOzS:-KwKLdOMW1hObTA_4xRH:b8otyau) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L378)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

is this FIXME still relevant?
</blockquote></details>

Method is not used, removed

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java, line 400 at r4](https://reviewable.io:443/reviews/vaadin/testbench/925#-KwKL60KggnusMbvqT4Q:-KwKLhyHUCDDYTxccpqY:b8otyau) ([raw file](https://github.com/vaadin/testbench/blob/4e2d427f1fe38076715eb27022552671a6efcffa/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java#L400)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

is this FIXME still relevant?
</blockquote></details>

Method is not used, removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by vlukashov** [comment]
Reviewed 31 of 31 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by alvarezguille** [comment]
*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PrivateTB3Configuration.java, line 68 at r6](https://reviewable.io:443/reviews/vaadin/testbench/925#-Kw_KKEm260fr8RcXGa2:-Kw_KKEm260fr8RcXGa3:bg6296f) ([raw file](https://github.com/vaadin/testbench/blob/f3f8e998db1a7673317b3def567b037961460a21/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PrivateTB3Configuration.java#L68)):*
>         String username = System.getenv("SAUCE_USERNAME");
>         String accessKey = System.getenv("SAUCE_ACCESS_KEY");

should we use `getProperty` for consistency and also to allow user to define java property in command line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by alvarezguille** [comment]
*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PrivateTB3Configuration.java, line 68 at r6](https://reviewable.io:443/reviews/vaadin/testbench/925#-Kw_KKEm260fr8RcXGa2:-Kw_LAf_g9avgEtymMDK:b-8hushi) ([raw file](https://github.com/vaadin/testbench/blob/f3f8e998db1a7673317b3def567b037961460a21/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PrivateTB3Configuration.java#L68)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>         String username = System.getenv("SAUCE_USERNAME");
>         String accessKey = System.getenv("SAUCE_ACCESS_KEY");

should we use `getProperty` for consistency and also to allow user to define java property in command line?
</blockquote></details>

That would also mean changing the property name to something like `sauce.username` so that it's used as `-Dsauce.username=...`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by Artur-** [comment]
Review status: 38 of 49 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PrivateTB3Configuration.java, line 68 at r6](https://reviewable.io:443/reviews/vaadin/testbench/925#-Kw_KKEm260fr8RcXGa2:-KwcovBjx02m9i28Z7UA:b3mkwq2) ([raw file](https://github.com/vaadin/testbench/blob/f3f8e998db1a7673317b3def567b037961460a21/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PrivateTB3Configuration.java#L68)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

That would also mean changing the property name to something like `sauce.username` so that it's used as `-Dsauce.username=...`
</blockquote></details>

SAUCE_USERNAME and SAUCE_ACCESS_KEY env variables are used because they are supported by the Maven plugin directly but sure we could change them to system properties like everything else

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 31 files at r5, 10 of 11 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/925)*

**Pull request merged**
