### PR TITLE
Change showTooltip to wait for tooltip to appear

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/877)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/elements/TestbenchElementTooltipIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/testbench/877#-KfMVGBFgkBgaeTnG455:-KfMVGBFgkBgaeTnG456:byp1ktf) ([raw file](https://github.com/vaadin/testbench/blob/75174687a56823d80452a86f510dfbdb4b6e43df/testbench-integration-tests/src/test/java/com/vaadin/tests/elements/TestbenchElementTooltipIT.java#L18)):*
> ```Java
> 
>     @Test
>     public void elementCompareScreen() throws Exception {
> ```

Rename

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/elements/TestbenchElementTooltipIT.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/testbench/877#-KfMVVVPIITnmlv79nXR:-KfMVVVPIITnmlv79nXS:b-2djx2a) ([raw file](https://github.com/vaadin/testbench/blob/75174687a56823d80452a86f510dfbdb4b6e43df/testbench-integration-tests/src/test/java/com/vaadin/tests/elements/TestbenchElementTooltipIT.java#L28)):*
> ```Java
> 
>         Assert.assertEquals("Tooltip",tooltipText);
>     }
> ```

There should be another test when you 
1. Show tooltip for component 1
2. Show tooltip for component 2
3. Verify that tooltip for component 2 and not component 1 is shown

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 173 at r1](https://reviewable.io:443/reviews/vaadin/testbench/877#-KfMVNGK2UXsWOTEYucF:-KfMVNGK2UXsWOTEYucG:bmfn1wt) ([raw file](https://github.com/vaadin/testbench/blob/75174687a56823d80452a86f510dfbdb4b6e43df/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L173)):*
> ```Java
>             .moveToElement(actualElement).perform();
> 
>         new WebDriverWait(getDriver(), 3)
> ```

Is 3s always enough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/877)*

**Comment by rogozinds** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/elements/TestbenchElementTooltipIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/testbench/877#-KfMVGBFgkBgaeTnG455:-KfM_ouNiwqhcxYlvk2X:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/75174687a56823d80452a86f510dfbdb4b6e43df/testbench-integration-tests/src/test/java/com/vaadin/tests/elements/TestbenchElementTooltipIT.java#L18)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/elements/TestbenchElementTooltipIT.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/testbench/877#-KfMVVVPIITnmlv79nXR:-KfM_pA_sk_JGzaMP6N1:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/75174687a56823d80452a86f510dfbdb4b6e43df/testbench-integration-tests/src/test/java/com/vaadin/tests/elements/TestbenchElementTooltipIT.java#L28)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

There should be another test when you 
1. Show tooltip for component 1
2. Show tooltip for component 2
3. Verify that tooltip for component 2 and not component 1 is shown
</blockquote></details>

Done.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 173 at r1](https://reviewable.io:443/reviews/vaadin/testbench/877#-KfMVNGK2UXsWOTEYucF:-KfM_sRd4_67daPBOQO3:bie7y3s) ([raw file](https://github.com/vaadin/testbench/blob/75174687a56823d80452a86f510dfbdb4b6e43df/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L173)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Is 3s always enough?
</blockquote></details>

it was 0.75  before

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/877)*

**Comment by rogozinds** [comment]
Don't merge, does not work in IE11

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/877#-:-KfMwwdJzdAAU_oJ6WAK:bavz2p1)*

**Comment by rogozinds** [comment]
Turned out that the new tests won't pass with previous code neither.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/877#-:-KfQFQfIhkM9yrIH937h:bd0bp2b)*

**Comment by alvarezguille** [comment]
what was the decision here? does it require a special fix for IE?

**Comment by Artur-** [comment]
No reaction in half a year, please reopen if this is still relevant

**Pull request closed without merging**
