### PR TITLE
Add info about GeckoDriver setup

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/857)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/setup/testbench-installation.asciidoc, line 117 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ70T7Eldq9YaBQ_tz0:-KZ70T7Eldq9YaBQ_tz1:btwgsnx) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L117)):*
> ```AsciiDoc
> 
> +
> http://chromedriver.storage.googleapis.com/index.html
> ```

Hardly

---

*[documentation/setup/testbench-installation.asciidoc, line 123 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ70aCu5yxfB_5tv8JQ:-KZ70aCu5yxfB_5tv8JR:bmd8xqn) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L123)):*
> ```AsciiDoc
> 
> +
> https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
> ```

This should be above?

---

*[documentation/setup/testbench-installation.asciidoc, line 135 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ70w9GjwOQyOQcZc1K:-KZ70w9GjwOQyOQcZc1L:b-6ldxkn) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L135)):*
> ```AsciiDoc
> * Chrome: [parameter]#webdriver.chrome.driver#
> * Firefox: [parameter]#webdriver.gecko.driver#
> * Microsoft Edge: [parameter]#webdriver.edge.driver#
> ```

Why is it "Microsoft Edge" but not "Google Chrome" and "Mozilla Firefox"?

---

*[documentation/setup/testbench-installation.asciidoc, line 137 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ70lKHc9KrUuQPPUoY:-KZ70lKHc9KrUuQPPUoZ:bojwkx1) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L137)):*
> ```AsciiDoc
> * Microsoft Edge: [parameter]#webdriver.edge.driver#
> * Internet Explorer: [parameter]#webdriver.ie.driver#
> * PhantomJS: [parameter]#phantomjs.binary.path#
> ```

Why is the PhantomJS binary path here when the other ones are paths to the web driver?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/857)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[documentation/testbench-quickstart.asciidoc, line 30 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ82uR_ABIGYdNIK_ra:-KZ82uR_ABIGYdNIK_rb:b-1bzc1z) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/testbench-quickstart.asciidoc#L30)):*
> ```AsciiDoc
> 
> [NOTE]
> Before Testbench version 5.0.0, Firefox did not require a web driver setup.
> ```

TestBench

---

*[documentation/testbench-tutorial.asciidoc, line 124 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ84NhHSzao_35sg0wc:-KZ84NhHSzao_35sg0wd:b-1bzc1z) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/testbench-tutorial.asciidoc#L124)):*
> ```AsciiDoc
> 
> [NOTE]
> Before Testbench version 5.0.0, Firefox did not require a web driver setup.
> ```

TestBench

---

*[documentation/setup/testbench-installation.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ85IyE7DnrlfeoMcR-:-KZ85IyE7DnrlfeoMcR0:by9w2xn) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L98)):*
> Whether developing tests with the WebDriver in the workstation or running tests
> in a grid, for different browsers requires the browser driver to be installed.

Last phrase doesn't sound right

---

*[documentation/setup/testbench-installation.asciidoc, line 130 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ86k2-ZHpRmZuU2AAh:-KZ86k2-ZHpRmZuU2AAi:b-iqmv03) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L130)):*
>  be given with a
or be given...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/857)*

**Comment by rogozinds** [comment]
Review status: 1 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[documentation/testbench-quickstart.asciidoc, line 30 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ82uR_ABIGYdNIK_ra:-KZMUer2hHaxOKW6Jsq8:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/testbench-quickstart.asciidoc#L30)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

TestBench
</blockquote></details>

Done.

---

*[documentation/testbench-tutorial.asciidoc, line 124 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ84NhHSzao_35sg0wc:-KZMdi9260AdHUmruD-h:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/testbench-tutorial.asciidoc#L124)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

TestBench
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ85IyE7DnrlfeoMcR-:-KZMYJfkxNHXeyUEi69X:b499q7j) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L98)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> Whether developing tests with the WebDriver in the workstation or running tests
> in a grid, for different browsers requires the browser driver to be installed.

Last phrase doesn't sound right
</blockquote></details>

Changed

---

*[documentation/setup/testbench-installation.asciidoc, line 117 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ70T7Eldq9YaBQ_tz0:-KZMYeFunuOTnG59L7aX:b-lruup) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L117)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Hardly
</blockquote></details>

Changed to the link to a latest release

---

*[documentation/setup/testbench-installation.asciidoc, line 123 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ70aCu5yxfB_5tv8JQ:-KZMZXQg4_JPJR6B077u:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L123)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This should be above?
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 130 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ86k2-ZHpRmZuU2AAh:-KZMZnq1ZtWy-8wYqiPk:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L130)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>  be given with a
or be given...
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 135 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ70w9GjwOQyOQcZc1K:-KZMdjZJDj5IJDxxGKpf:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L135)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why is it "Microsoft Edge" but not "Google Chrome" and "Mozilla Firefox"?
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 137 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ70lKHc9KrUuQPPUoY:-KZMddSa6mYVsUaJ9-KP:b-kposql) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L137)):*
> Mozilla
added ghostdriver path property setup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/857)*

**Comment by Artur-** [comment]
Reviewed 1 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[documentation/testbench-quickstart.asciidoc, line 30 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ82uR_ABIGYdNIK_ra:-KZQGJWe1eLuH-nHg_Fc:b-sdfwd1) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/testbench-quickstart.asciidoc#L30)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still says "Testbench"

---

*[documentation/setup/testbench-installation.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ85IyE7DnrlfeoMcR-:-KZQF7C-Ga_Ufifa9PJX:bz71exv) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L98)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> Whether developing tests with the WebDriver in the workstation or running tests
> in a grid, for different browsers requires the browser driver to be installed.

Last phrase doesn't sound right
</blockquote></details>

How about "Each browser requires a browser specific web driver to be installed before tests can be run" or something similar?

---

*[documentation/setup/testbench-installation.asciidoc, line 101 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQFaHVxvvvuOQa2_SG:-KZQFaHVxvvvuOQa2_SH:b-3ltc97) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L101)):*
> ```AsciiDoc
> . Download the latest browser driver
> 
> ** Firefox - install GeckoDriver for your platform from under the latest release at:
> ```

Remove "under"

---

*[documentation/setup/testbench-installation.asciidoc, line 107 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQFdI7GdQyOJY1e4o4:-KZQFdI7GdQyOJY1e4o5:b-3ltc97) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L107)):*
> ```AsciiDoc
> 
> ** Chrome - install ChromeDriver (a part of the Chromium project) for your platform
> from under the latest release at:
> ```

Remove "under"

---

*[documentation/setup/testbench-installation.asciidoc, line 113 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQFfbCZpOzvutMD2QO:-KZQFfbCZpOzvutMD2QP:b-3ltc97) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L113)):*
> ```AsciiDoc
> 
> ** Microsoft Edge - install MicrosoftWebDriver for your platform
> from under the latest release at:
> ```

Remove "under"

---

*[documentation/setup/testbench-installation.asciidoc, line 119 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQEPpY6Qv2teC-IZSY:-KZQEPpZcqaM0Ht68Xxh:b-3ltc97) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L119)):*
> ```AsciiDoc
> 
> ** Internet Explorer (Windows only) - install [filename]#IEDriverServer.exe# from
> under the latest Selenium release:
> ```

Remove "under"

---

*[documentation/setup/testbench-installation.asciidoc, line 127 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQFtP2BacCEAUyluDG:-KZQFtP2BacCEAUyluDH:b-5en5uc) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L127)):*
> ```AsciiDoc
> 
> [[testbench.installation.browserdrivers.addingtopath]]
> === Adding Web Driver to a System Path
> ```

remove "a"

---

*[documentation/setup/testbench-installation.asciidoc, line 144 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQG-8o80kYT4F7E8k6:-KZQG-8o80kYT4F7E8k7:b3tdbkp) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L144)):*
> ```AsciiDoc
> 
> If you use an ESR version of Firefox, which is recommended for test stability,
> you need to the binary when creating the driver as follows:
> ```

"you need to refer to the binary"?

---

*[documentation/setup/testbench-installation.asciidoc, line 149 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQG3F0kgDbHzplmSQ8:-KZQG3F0kgDbHzplmSQ9:bmc1dba) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L149)):*
> ```AsciiDoc
> ----
> FirefoxBinary binary =
>     new FirefoxBinary(new File("/path/to/firefox_ESR_10"));
> ```

Maybe use 45 instead of 10 as an example

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/857)*

**Comment by rogozinds** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[documentation/testbench-quickstart.asciidoc, line 30 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ82uR_ABIGYdNIK_ra:-KZQVx1DTLh49qIpptXK:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/testbench-quickstart.asciidoc#L30)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Still says "Testbench"
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZ85IyE7DnrlfeoMcR-:-KZQV6R4q8p5WFWHMzqw:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/b7fd6866d410e0afab00bf836aefa028dfa29834/documentation/setup/testbench-installation.asciidoc#L98)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

How about "Each browser requires a browser specific web driver to be installed before tests can be run" or something similar?
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 101 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQFaHVxvvvuOQa2_SG:-KZQVHLD525XTOiLbL4_:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L101)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Remove "under"
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 107 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQFdI7GdQyOJY1e4o4:-KZQVHeM6wsADBzkj9yp:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L107)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Remove "under"
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 113 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQFfbCZpOzvutMD2QO:-KZQVL9JyjX07klTbpuk:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L113)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Remove "under"
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 119 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQEPpY6Qv2teC-IZSY:-KZQVNcMAJ82_MhaM858:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L119)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Remove "under"
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 127 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQFtP2BacCEAUyluDG:-KZQVROdEF_ds18Yet-j:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L127)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

remove "a"
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 144 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQG-8o80kYT4F7E8k6:-KZQVaC--FffCmf9sGD0:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L144)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

"you need to refer to the binary"?
</blockquote></details>

Done.

---

*[documentation/setup/testbench-installation.asciidoc, line 149 at r2](https://reviewable.io:443/reviews/vaadin/testbench/857#-KZQG3F0kgDbHzplmSQ8:-KZQVe1SrOSS6TI3wmIP:bcil0fx) ([raw file](https://github.com/vaadin/testbench/blob/d71e172c74639a2032fa669bf98d3bbe0e62d1c9/documentation/setup/testbench-installation.asciidoc#L149)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Maybe use 45 instead of 10 as an example
</blockquote></details>

Yeah nice idea :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/857)*

**Comment by Artur-** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/857)*

**Pull request merged**
