### PR TITLE
Update release notes for 5.0.0.alpha1

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/844)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[doc/releasenotes.html, line 478 at r1](https://reviewable.io:443/reviews/vaadin/testbench/844#-KXKgGkvphtQkngEas5P:-KXKgGkw1Ak9vgF3bKRO:brk7od7) ([raw file](https://github.com/vaadin/testbench/blob/6d0b1e70a61e29c4e38eb9f52d275e51bacd488f/doc/releasenotes.html#L478)):*
> ```HTML
> 
>     <p>Vaadin TestBench is a UI browser automation tool used for automated testing of Vaadin UIs in the browser. Vaadin
>         TestBench is based on Selenium 2 and provides a WebDriver based API for controlling different browsers on
> ```

Remove "2"

---

*[doc/releasenotes.html, line 519 at r1](https://reviewable.io:443/reviews/vaadin/testbench/844#-KXKgAOea9H5vvMqUX8u:-KXKgAOea9H5vvMqUX8v:b-5en6yt) ([raw file](https://github.com/vaadin/testbench/blob/6d0b1e70a61e29c4e38eb9f52d275e51bacd488f/doc/releasenotes.html#L519)):*
> ```HTML
>                 <pre>vaadin-testbench-standalone-${project.version}.jar</pre>
>             </td>
>             <td>This is the standalone version of the Vaadin TestBench library. It includes the Selenium 2 WebDriver
> ```

remove "2"

---

*[doc/releasenotes.html, line 531 at r1](https://reviewable.io:443/reviews/vaadin/testbench/844#-KXKg9589QsPGs_zxRHb:-KXKg9589QsPGs_zxRHc:b3kr4) ([raw file](https://github.com/vaadin/testbench/blob/6d0b1e70a61e29c4e38eb9f52d275e51bacd488f/doc/releasenotes.html#L531)):*
> ```HTML
>     <p>All dependencies, along with their dependencies are bundled in <code>vaadin-testbench-standalone-${project.version}.jar</code>.
>         The maven directory also contains <code>vaadin-testbench-${project.version}.jar</code>, which does not bundle
>         any dependencies. Vaadin TestBench 4 directly depends on the following third-party libraries:</p>
> ```

5

---

*[doc/releasenotes.html, line 554 at r1](https://reviewable.io:443/reviews/vaadin/testbench/844#-KXKg68GMhtG7g2FtL88:-KXKg68GMhtG7g2FtL89:b3kr4) ([raw file](https://github.com/vaadin/testbench/blob/6d0b1e70a61e29c4e38eb9f52d275e51bacd488f/doc/releasenotes.html#L554)):*
> ```HTML
>     <h2 id="supported_platforms_and_browsers">Supported Platforms and Browsers</h2>
> 
>     <p>Vaadin TestBench 4 fully supports Windows, Mac OS X and Linux as well as iOS and Android for running tests. The
> ```

5

---

*[doc/releasenotes.html, line 559 at r1](https://reviewable.io:443/reviews/vaadin/testbench/844#-KXKg1buNSZHOt4-mXbQ:-KXKg1buNSZHOt4-mXbR:b-is41w3) ([raw file](https://github.com/vaadin/testbench/blob/6d0b1e70a61e29c4e38eb9f52d275e51bacd488f/doc/releasenotes.html#L559)):*
> ```HTML
>     <ul>
>         <li>Latest Google Chrome</li>
>         <li>Internet Explorer 8, 9, 10, 11</li>
> ```

IE 11 only

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/844)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[doc/releasenotes.html, line 478 at r1](https://reviewable.io:443/reviews/vaadin/testbench/844#-KXKgGkvphtQkngEas5P:-KXKgysLyAu13aMKdJ3N:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/152fa2d932b52f843110c38b55f3d6dc1a283d03/doc/releasenotes.html#L478)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Remove "2"
</details>
Done.

---

*[doc/releasenotes.html, line 519 at r1](https://reviewable.io:443/reviews/vaadin/testbench/844#-KXKgAOea9H5vvMqUX8u:-KXKh1oLSh3pWBCz5he9:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/152fa2d932b52f843110c38b55f3d6dc1a283d03/doc/releasenotes.html#L519)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> remove "2"
</details>
Done.

---

*[doc/releasenotes.html, line 531 at r1](https://reviewable.io:443/reviews/vaadin/testbench/844#-KXKg9589QsPGs_zxRHb:-KXKh5uHPyRrZdbjHH8Q:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/152fa2d932b52f843110c38b55f3d6dc1a283d03/doc/releasenotes.html#L531)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> 5
</details>
Done.

---

*[doc/releasenotes.html, line 554 at r1](https://reviewable.io:443/reviews/vaadin/testbench/844#-KXKg68GMhtG7g2FtL88:-KXKhDbtFoKi5_10SXRi:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/152fa2d932b52f843110c38b55f3d6dc1a283d03/doc/releasenotes.html#L554)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> 5
</details>
Done.

---

*[doc/releasenotes.html, line 559 at r1](https://reviewable.io:443/reviews/vaadin/testbench/844#-KXKg1buNSZHOt4-mXbQ:-KXKhE2ltiPpMsc91VXN:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/152fa2d932b52f843110c38b55f3d6dc1a283d03/doc/releasenotes.html#L559)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> IE 11 only
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/844)*

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/844)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/844)*

**Pull request merged**
