### PR TITLE
Initial changes of Vaadin 8 support

### PR DESCRIPTION
**Pull request by alvarezguille**
Update to alpha6
Update jetty, vaadin and java version.
Fix compilation errors.
Fix most test UI
Ignore counted failing tests

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/816)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 56 of 56 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxGetSuggestions.java, line 17 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDUTYpc1Hoix1WPL5L:-KWDUTYqpg3QIQLI9987:b-xkfyvc) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxGetSuggestions.java#L17)):*
> ```Java
>         ComboBox<String> cb = new ComboBox<String>();
>         cb.setEmptySelectionAllowed(false);
>         // cb.setInvalidAllowed(false);
> ```

Remove commented out code

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDVh_ClH2VIZE-qgNO:-KWDVh_Dv3DdIzvFtfKw:b-xkfyvc) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java#L30)):*
> ```Java
>         select.select("item1");
>         select.addSelectionListener(new CounterListener(counterLbl, 0));
>         // select.setNullSelectionAllowed(false);
> ```

Remove commented out code

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDVimvREwAuN_wWoDV:-KWDVimvREwAuN_wWoDW:b-xkfyvc) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java#L37)):*
> ```Java
> 
>         ListSelect multiSelect = new ListSelect();
>         // multiSelect.setMultiSelect(true);
> ```

Remove commented out code

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDVkS6wb67b6b9-vpX:-KWDVkS6wb67b6b9-vpY:b-xkfyvc) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java#L47)):*
> ```Java
>         multiSelect
>                 .addSelectionListener(new CounterListener(multiCounterLbl, 0));
>         // multiSelect.setNullSelectionAllowed(false);
> ```

Remove commented out code

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/TestUIProvider.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDW4ZJqd833PmnQlkP:-KWDW4ZJqd833PmnQlkQ:b6c4d4s) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/TestUIProvider.java#L22)):*
> ```Java
>             String className = "com.vaadin.testUI." + name;
>             return Class.forName(className).asSubclass(UI.class);
>         } catch (ClassNotFoundException e) {
> ```

Handle exception

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/abstracttextfield/AbstractTextElementSetValueIT.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDWzKesBtY_ffbVNhW:-KWDWzKf5Sjii46wF0hm:b-cv2pm4) ([raw file](https://github.com/vaadin/testbench/blob/49c8aeb7bfc6312ba89370347c494eb4ad958b5c/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/abstracttextfield/AbstractTextElementSetValueIT.java#L62)):*
> ```Java
> 
>     @Test
>     public void dateFieldSetValue() {
> ```

Where did this go?

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/grid/GridUIIT.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDXCwhRVnhFCY4Fwwb:-KWDXCwiihrivjbR5-46:b5o3soi) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/grid/GridUIIT.java#L35)):*
> ```Java
> 
>     @Test
>     @Ignore("API needed for getRows working is missing in FW8 ATM")
> ```

"There is a bug in alpha6 which prevents this from working"

---

*[vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDW_MOUNALLTQ1UzyZ:-KWDW_MPRmfVs_BuNj73:b-vjk5bw) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java#L45)):*
> ```Java
>                 + "Vaadin TestBench 4 registered to .*" + NEW_LINE + "-*("
>                 + NEW_LINE + ")*";
>         System.out.println(output);
> ```

but why

---

*[vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDWb_iyDnrVi7WdHsR:-KWDWb_iyDnrVi7WdHsS:bm1h47c) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java#L73)):*
> ```Java
>         String expectingMessage = "---------------------------------------------------------------------------------"
>                 + NEW_LINE
>                 + "License for Vaadin TestBench 5 not found. Go to vaadin.com/pro for more details."
> ```

A constant, prehups?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/816)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxGetSuggestions.java, line 17 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDUTYpc1Hoix1WPL5L:-KWH8FTHq7wHzhl_iwG4:b-faclxb) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxGetSuggestions.java#L17)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Remove commented out code
</details>
commented code is missing API in this case

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDVh_ClH2VIZE-qgNO:-KWH8Ql019iLJb8xzSCB:b-faclxb) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java#L30)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Remove commented out code
</details>
commented code is missing API in this case

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDVimvREwAuN_wWoDV:-KWH8WlyNojACKBoYwH-:bbe77k8) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java#L37)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Remove commented out code
</details>
in this case it was the default value, I'll change it

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDVkS6wb67b6b9-vpX:-KWH8cWo8wzSHt4-hzbd:b-faclxb) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java#L47)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Remove commented out code
</details>
commented code is missing API in this case

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/TestUIProvider.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDW4ZJqd833PmnQlkP:-KWH9I9fF-TuJZAO0pTK:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/TestUIProvider.java#L22)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Handle exception
</details>
Done.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/abstracttextfield/AbstractTextElementSetValueIT.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDWzKesBtY_ffbVNhW:-KWHTAseAHGzU-WqJ2Ez:b-sggu7a) ([raw file](https://github.com/vaadin/testbench/blob/49c8aeb7bfc6312ba89370347c494eb4ad958b5c/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/abstracttextfield/AbstractTextElementSetValueIT.java#L62)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Where did this go?
</details>
it's back, although FW behavior changed and test had to be adjusted

---

*[vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDW_MOUNALLTQ1UzyZ:-KWHTNrbXi5prGcN5mpI:b-51zprm) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java#L45)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> but why
</details>
you didn't see that 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/816)*

**Comment by alvarezguille** [comment]
Review status: 51 of 56 files reviewed at latest revision, 5 unresolved discussions.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/grid/GridUIIT.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDXCwhRVnhFCY4Fwwb:-KWHUSrwb_leGY8DOynB:b32wtd) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/grid/GridUIIT.java#L35)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> "There is a bug in alpha6 which prevents this from working"
</details>
ok

---

*[vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDW_MOUNALLTQ1UzyZ:-KWHUijv-1aH4GT2Arr1:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java#L45)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> you didn't see that 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/816)*

**Comment by Artur-** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxGetSuggestions.java, line 17 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDUTYpc1Hoix1WPL5L:-KWHUPRquftkBrDK2JoO:b-blrab7) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxGetSuggestions.java#L17)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> commented code is missing API in this case
</details>
What is missing? There won't be any "invalidAllowed" because a ComboBox in 8 does not have validators, and "newItemsAllowed" is set to false here, which should be the default

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDVh_ClH2VIZE-qgNO:-KWHUWNsOKNEwBcKmw8I:b-krqsmc) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java#L30)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> commented code is missing API in this case
</details>
Isn't null/empty selection disallowed by default?

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDVkS6wb67b6b9-vpX:-KWHUgMNlWEUSJc8OizQ:b-krqsmc) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java#L47)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> commented code is missing API in this case
</details>
Isn't null/empty selection disallowed by default?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/816)*

**Comment by alvarezguille** [comment]
*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxGetSuggestions.java, line 17 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDUTYpc1Hoix1WPL5L:-KWIGCRrGU7hXL2rIsk0:b32wtd) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxGetSuggestions.java#L17)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> What is missing? There won't be any "invalidAllowed" because a ComboBox in 8 does not have validators, and "newItemsAllowed" is set to false here, which should be the default
</details>
ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/816)*

**Comment by alvarezguille** [comment]
Review status: 50 of 56 files reviewed at latest revision, 4 unresolved discussions.

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDVh_ClH2VIZE-qgNO:-KWIGT3AirkSIfDkWmR0:b-z4kpve) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java#L30)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Isn't null/empty selection disallowed by default?
</details>
actually empty selection is allowed and can't be disabled in FW8

---

*[testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDVkS6wb67b6b9-vpX:-KWIGzOR99Vc9ZCw7674:b-z4kpve) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java#L47)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Isn't null/empty selection disallowed by default?
</details>
actually empty selection is allowed and can't be disabled in FW8

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/816)*

**Comment by Artur-** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/816)*

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 46 of 56 files at r1, 4 of 5 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/testbench/816#-KWDWb_iyDnrVi7WdHsR:-KWIPlU4EaCSLSqEEwXl:bq0nsa2) ([raw file](https://github.com/vaadin/testbench/blob/45e8e211d582a915fc4ff701953998f250e23576/vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java#L73)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> A constant, prehups?
</details>
Doesn't make a lot of sense to have a constant, as the whole message is already a constant :).
Would be nice of course if it's would be taken from project version, but that's a separate issue IMO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/816#-:-KWIQBlLXkA3BTUoQlY_:bnfp4nl)*

**Pull request merged**
