### PR TITLE
Add a runtime check that the expected Selenium version is found

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/961)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-standalone/lib/upgrade.txt, line 7 at r1](https://reviewable.io:443/reviews/vaadin/testbench/961#-Kyq8x43NRkxleP8JQgU:-Kyq8x43NRkxleP8JQgV:bt3lynp) ([raw file](https://github.com/vaadin/testbench/blob/fbb388057c9db7c4f7263ccea25928c03d0f8932/vaadin-testbench-standalone/lib/upgrade.txt#L7)):*
> - update SELENIUM_VERSION in TestBenchTestCase.java

Can we use avoid this step by using the same approach as in charts https://github.com/vaadin/charts/commit/286085a99a7f3d6d326cdd455f5ba739ddbc9a3c
?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/961)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-standalone/lib/upgrade.txt, line 7 at r1](https://reviewable.io:443/reviews/vaadin/testbench/961#-Kyq8x43NRkxleP8JQgU:-KyuHAE0tCeKneDZf4Sh:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/fbb388057c9db7c4f7263ccea25928c03d0f8932/vaadin-testbench-standalone/lib/upgrade.txt#L7)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> - update SELENIUM_VERSION in TestBenchTestCase.java

Can we use avoid this step by using the same approach as in charts https://github.com/vaadin/charts/commit/286085a99a7f3d6d326cdd455f5ba739ddbc9a3c
?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/961)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 3 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/961)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/961)*

**Pull request merged**
