### PR TITLE
Run jetty in production mode for IE11 support

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/939)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/939#-KxgJJFdcAB-gnVOfPvi:-KxgJJFdcAB-gnVOfPvj:bcu1zqm) (no related file):*
Is there a good reason for not doing the ES5 serving as explained in [flow docs](https://github.com/vaadin/flow/blob/master/flow-documentation/web-components/tutorial-webcomponents-es5.asciidoc)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/939)*

**Comment by Artur-** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/939#-KxgJJFdcAB-gnVOfPvi:-KxgL0IXVFwtAFQW3IHN:b-dfi6ge) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

Is there a good reason for not doing the ES5 serving as explained in [flow docs](https://github.com/vaadin/flow/blob/master/flow-documentation/web-components/tutorial-webcomponents-es5.asciidoc)?
</blockquote></details>

Isn't it done that way? 
```
In production, the Flow application will determine whether the browser supports ES6 or not. When the browser supports ES6, the linked file will be served from (context)/frontend-es6/components/my-component.html. When it doesn`t, the served file will be (context)/frontend-es5/components/my-component.html.
```

The transpiled files here end up in `(context)/frontend-es6` and `(context)/frontend-es5`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/939)*

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/939#-KxgJJFdcAB-gnVOfPvi:-KxgN7yCVw08LcxX_Df4:b-4kpmjh) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Isn't it done that way? 
```
In production, the Flow application will determine whether the browser supports ES6 or not. When the browser supports ES6, the linked file will be served from (context)/frontend-es6/components/my-component.html. When it doesn`t, the served file will be (context)/frontend-es5/components/my-component.html.
```

The transpiled files here end up in `(context)/frontend-es6` and `(context)/frontend-es5`
</blockquote></details>

that's just one paragraph of the `Linking both ES6 and ES5 files in your application` where the `frontend.url.es6` and `frontend.url.es5` properties are introduced, but you're right with vaadin/flow#2801 that there are some outdated details in the tutorial I linked

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/939)*

**Comment by alvarezguille** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/939)*

**Pull request merged**
