### PR TITLE
Changed BrowserFactory to use Firefox 45

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/871)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/elements/VaadinBrowserFactory.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/testbench/871#-KcNN8e1UMO675UrZknW:-KcNN8e1UMO675UrZknX:bukblff) ([raw file](https://github.com/vaadin/testbench/blob/217548473a40993e949d3a5fdffb61ffa3313f6b/testbench-integration-tests/src/test/java/com/vaadin/tests/elements/VaadinBrowserFactory.java#L76)):*
> "marionette"
use magic constant instead of magic string
> "false"
use magic native boolean  instead of magic string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/871)*

**Comment by rogozinds** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/elements/VaadinBrowserFactory.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/testbench/871#-KcNN8e1UMO675UrZknW:-KcNOlLfjF-iqNgVnEBT:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/217548473a40993e949d3a5fdffb61ffa3313f6b/testbench-integration-tests/src/test/java/com/vaadin/tests/elements/VaadinBrowserFactory.java#L76)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> "marionette"
use magic constant instead of magic string
> "false"
use magic native boolean  instead of magic string
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/871)*

**Comment by rogozinds** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/elements/VaadinBrowserFactory.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/testbench/871#-KcNN8e1UMO675UrZknW:-KcNOyK4nJIp1Fngbexr:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/217548473a40993e949d3a5fdffb61ffa3313f6b/testbench-integration-tests/src/test/java/com/vaadin/tests/elements/VaadinBrowserFactory.java#L76)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/871)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/871)*

**Pull request merged**
