### PR TITLE
Add helper for executing JavaScript

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/883)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/883)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/883#-KiAHUOqtIGOkOV29hni:-KiAHUOqtIGOkOV29hnj:b5xl297) (no related file):*
Maybe an example of this should be added to docs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/883)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/883#-KiAHUOqtIGOkOV29hni:-KjvoFJgCKf17zJF_jiO:b-6a8pix) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

Maybe an example of this should be added to docs
</blockquote></details>

Of executing JS? Where would that go and what should it contain?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/883)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/883#-KiAHUOqtIGOkOV29hni:-KjvoOK572rChS_zLp1f:b9f1ko9) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Of executing JS? Where would that go and what should it contain?
</blockquote></details>

"Special Testing Topcis" -> "Executing Javascript" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/883)*

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/883#-KiAHUOqtIGOkOV29hni:-KjvryK7Axx7nR89kqIn:b-vzalql) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

"Special Testing Topcis" -> "Executing Javascript" ?
</blockquote></details>

That looks like a good place yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/883)*

**Comment by svenruppert** [comment]
Reviewed 3 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/883)*

**Comment by svenruppert** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/883#-:-KlSVOHEmap7BK3ACgbH:bnfp4nl)*

**Comment by svenruppert** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/883#-KiAHUOqtIGOkOV29hni:-KlSV_WzVypj3kQ1aQU8:b-h8hc1h) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

That looks like a good place yes
</blockquote></details>

so far i saw it it was done..  

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/883)*

**Comment by svenruppert** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/883#-KiAHUOqtIGOkOV29hni:-KlSW6NaZkZuPi65xhRl:b67jwmz) (no related file):*
<details><summary><i>Previously, svenruppert (Sven Ruppert) wrote…</i></summary><blockquote>

so far i saw it it was done..  

ok
</blockquote></details>

ups..  dismissed be accident..  sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/883)*

**Pull request merged**
