### PR TITLE
Fix usage of deprecated DesiredCapabilities methods

### LINKED ISSUE #1016: Fix deprecation warnings when running tests
```
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
```
and similar pop up for all `ParallelTest`s

### PR DESCRIPTION
**Pull request by johannesh2**
Fixes #1016

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/1029)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/1029#-L871_wmpFdYgerE0-3n:-L871_wnY7cKmKpwYWQF:bu51lwe) (no related file):*
this seems to be affecting FF on saucelabs quite badly
https://bender.vaadin.com/viewLog.html?buildId=9111

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/1029)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/DefaultBrowserFactory.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/testbench/1029#-L8HC4X-66P1UcE-y-2_:-L8HC4X-66P1UcE-y-2a:bbovqru) ([raw file](https://github.com/vaadin/testbench/blob/4ce33011d2999de914cafb30b5fa88ecc311b9a7/vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/DefaultBrowserFactory.java#L62)):*
> ```Java
>             desiredCapabilities.setCapability(CapabilityType.VERSION,
>                     version);
>             desiredCapabilities.setCapability(CapabilityType.PLATFORM_NAME,
> ```

Why is this changed from `platform` to `platformName`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/1029)*

**Comment by johannesh2** [comment]
*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/DefaultBrowserFactory.java, line 62 at r1](https://beta.reviewable.io/reviews/vaadin/testbench/1029#-L8HC4X-66P1UcE-y-2_:-L8YYV0YAk_nVPpx6j65:b-fg1nb0) ([raw file](https://github.com/vaadin/testbench/blob/fbbd5127fc3fa87463362e0ea06f46f25ff419a6/vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/DefaultBrowserFactory.java#L62)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why is this changed from `platform` to `platformName`?
</blockquote></details>

Platform is deprecated and getPlatform seems to accept both ways.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/testbench/1029)*

**Comment by johannesh2** [comment]
Fixed in another PR. Closing.

**Pull request closed without merging**
