### PR TITLE
Update to Selenium 3.0.1

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/828)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 3 of 9 files at r1.
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/AbstractTB3Test.java, line 718 at r1](https://reviewable.io:443/reviews/vaadin/testbench/828#-KXGFjH6rExOdbedI9Wa:-KXGFjH6rExOdbedI9Wb:b-fvzzoa) ([raw file](https://github.com/vaadin/testbench/blob/9c2baefc8f07fca49fb140d4aa693d36945951d5/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/AbstractTB3Test.java#L718)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>     public void hitButton(String id) {
>         if (BrowserUtil.isPhantomJS(getDesiredCapabilities())) {
>             driver.findElement(By.id(id)).click();
>         } else {
>             WebDriverBackedSelenium selenium = new WebDriverBackedSelenium(
>                     driver, driver.getCurrentUrl());
</details>
>  
>             selenium.keyPress("id=" + id, "\\13");
>         }
>     }
isn't this needed by FW?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/828)*

**Comment by Artur-** [comment]
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/AbstractTB3Test.java, line 718 at r1](https://reviewable.io:443/reviews/vaadin/testbench/828#-KXGFjH6rExOdbedI9Wa:-KXGHODWb3AYS49depHE:b-rawsrm) ([raw file](https://github.com/vaadin/testbench/blob/9c2baefc8f07fca49fb140d4aa693d36945951d5/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/AbstractTB3Test.java#L718)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> >     public void hitButton(String id) {
> >         if (BrowserUtil.isPhantomJS(getDesiredCapabilities())) {
> >             driver.findElement(By.id(id)).click();
> >         } else {
> >             WebDriverBackedSelenium selenium = new WebDriverBackedSelenium(
> >                     driver, driver.getCurrentUrl());
> >  
> >             selenium.keyPress("id=" + id, "\\13");
> >         }
> >     }
> isn't this needed by FW?
</details>
Needed for what?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/828)*

**Comment by alvarezguille** [comment]
*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/AbstractTB3Test.java, line 718 at r1](https://reviewable.io:443/reviews/vaadin/testbench/828#-KXGFjH6rExOdbedI9Wa:-KXGI5HtW3wdW5XCYeRa:b-tbye2b) ([raw file](https://github.com/vaadin/testbench/blob/9c2baefc8f07fca49fb140d4aa693d36945951d5/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/AbstractTB3Test.java#L718)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Needed for what?
</details>
IDK
but seems like we're talking about adding FW helpers to TB and deleting them at the same time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/828)*

**Comment by Artur-** [comment]
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/AbstractTB3Test.java, line 718 at r1](https://reviewable.io:443/reviews/vaadin/testbench/828#-KXGFjH6rExOdbedI9Wa:-KXGKYB15XlXFlB1KKQ_:biq825b) ([raw file](https://github.com/vaadin/testbench/blob/9c2baefc8f07fca49fb140d4aa693d36945951d5/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/AbstractTB3Test.java#L718)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> IDK
> but seems like we're talking about adding FW helpers to TB and deleting them at the same time
</details>
This is just a test class. Helpers in *Elements classes make sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/828)*

**Comment by alvarezguille** [comment]
Reviewed 6 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/828)*

**Pull request merged**
