### PR TITLE
Add docs about Firefox ESR and GeckoDriver

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/876)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/testbench-known-issues.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/testbench/876#-KfLU8JtdP-RzTczsNBu:-KfLU8JtdP-RzTczsNBv:bxe3nu4) ([raw file](https://github.com/vaadin/testbench/blob/f0dc2dd158d5ff094ee471293ba0f3e880ad80b8/documentation/testbench-known-issues.asciidoc#L19)):*
> ```AsciiDoc
> Geckodriver used for the latest Firefox versions (48 and newer) does not support link:https://github.com/mozilla/geckodriver/issues/159[actions API].
> In practice, meaning that you can not simulate context click and double click in tests.
> It is recommended to use either link:https://www.mozilla.org/en-US/firefox/organizations/all/[Firefox ESR] (currently at 45.3)
> ```

ESR is currently at 52 so this should be rephrased to say that you should use 45

---

*[documentation/testbench-known-issues.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/testbench/876#-KfLUJcOLYVq94t8eYtT:-KfLUJcOLYVq94t8eYtU:b-spp7vx) ([raw file](https://github.com/vaadin/testbench/blob/f0dc2dd158d5ff094ee471293ba0f3e880ad80b8/documentation/testbench-known-issues.asciidoc#L21)):*
> ```AsciiDoc
> It is recommended to use either link:https://www.mozilla.org/en-US/firefox/organizations/all/[Firefox ESR] (currently at 45.3)
> or link:https://ftp.mozilla.org/pub/firefox/releases/47.0.1/[Firefox 47] with GeckoDriver.
> You should use GeckoDriver in legacy mode with Firefox ESR and Firefox 47.
> ```

Please add something to answer the question "How do I use legacy mode"

---

*[documentation/testbench-quickstart.asciidoc, line 40 at r1](https://reviewable.io:443/reviews/vaadin/testbench/876#-KfLUU80X9bI4ZxYWS6i:-KfLUU80X9bI4ZxYWS6j:bs90xs2) ([raw file](https://github.com/vaadin/testbench/blob/f0dc2dd158d5ff094ee471293ba0f3e880ad80b8/documentation/testbench-quickstart.asciidoc#L40)):*
> ```AsciiDoc
> Geckodriver used for the latest Firefox versions (48 and newer) does not support link:https://github.com/mozilla/geckodriver/issues/159[actions API].
> In practice, meaning that you can not simulate context click and double click in tests.
> It is recommended you use link:https://www.mozilla.org/en-US/firefox/organizations/all/[Firefox ESR] to execute tests on Firefox, before this is fixed.
> ```

ESR 45

---

*[documentation/testbench-tutorial.asciidoc, line 132 at r1](https://reviewable.io:443/reviews/vaadin/testbench/876#-KfLUWo2YlBph-VHDlZQ:-KfLUWo2YlBph-VHDlZR:bs90xs2) ([raw file](https://github.com/vaadin/testbench/blob/f0dc2dd158d5ff094ee471293ba0f3e880ad80b8/documentation/testbench-tutorial.asciidoc#L132)):*
> ```AsciiDoc
> Geckodriver used for the latest Firefox versions (48 and newer) does not support link:https://github.com/mozilla/geckodriver/issues/159[actions API].
> In practice, meaning that you can not simulate context click and double click in tests.
> It is recommended you use link:https://www.mozilla.org/en-US/firefox/organizations/all/[Firefox ESR] to execute tests on Firefox, before this is fixed.
> ```

ESR 45

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/876)*

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/testbench-known-issues.asciidoc, line 18 at r1](https://reviewable.io:443/reviews/vaadin/testbench/876#-KfLUZn7hFWfqyrSWZlS:-KfLUZn7hFWfqyrSWZlT:bmqn3po) ([raw file](https://github.com/vaadin/testbench/blob/f0dc2dd158d5ff094ee471293ba0f3e880ad80b8/documentation/testbench-known-issues.asciidoc#L18)):*
> ```AsciiDoc
> Mozilla Firefox changed important APIs in version 48 that affected their compatibility with WebDriver which directly affects TestBench.
> Geckodriver used for the latest Firefox versions (48 and newer) does not support link:https://github.com/mozilla/geckodriver/issues/159[actions API].
> In practice, meaning that you can not simulate context click and double click in tests.
> ```

It also means that some parts of the Element API just will not work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/876)*

**Comment by rogozinds** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/testbench-known-issues.asciidoc, line 18 at r1](https://reviewable.io:443/reviews/vaadin/testbench/876#-KfLUZn7hFWfqyrSWZlS:-KfLXlf6CZHPNwn8cPsN:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/f0dc2dd158d5ff094ee471293ba0f3e880ad80b8/documentation/testbench-known-issues.asciidoc#L18)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

It also means that some parts of the Element API just will not work
</blockquote></details>

Done.

---

*[documentation/testbench-known-issues.asciidoc, line 19 at r1](https://reviewable.io:443/reviews/vaadin/testbench/876#-KfLU8JtdP-RzTczsNBu:-KfLXFyfyoUuQjlgVOuJ:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/f0dc2dd158d5ff094ee471293ba0f3e880ad80b8/documentation/testbench-known-issues.asciidoc#L19)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

ESR is currently at 52 so this should be rephrased to say that you should use 45
</blockquote></details>

Done.

---

*[documentation/testbench-known-issues.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/testbench/876#-KfLUJcOLYVq94t8eYtT:-KfLXH3gne5ofZDKfFBH:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/f0dc2dd158d5ff094ee471293ba0f3e880ad80b8/documentation/testbench-known-issues.asciidoc#L21)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Please add something to answer the question "How do I use legacy mode"
</blockquote></details>

Done.

---

*[documentation/testbench-quickstart.asciidoc, line 40 at r1](https://reviewable.io:443/reviews/vaadin/testbench/876#-KfLUU80X9bI4ZxYWS6i:-KfLXnVpYezFh3drAxAL:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/f0dc2dd158d5ff094ee471293ba0f3e880ad80b8/documentation/testbench-quickstart.asciidoc#L40)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

ESR 45
</blockquote></details>

Done.

---

*[documentation/testbench-tutorial.asciidoc, line 132 at r1](https://reviewable.io:443/reviews/vaadin/testbench/876#-KfLUWo2YlBph-VHDlZQ:-KfLY0RUrbQIGRIWh93Y:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/f0dc2dd158d5ff094ee471293ba0f3e880ad80b8/documentation/testbench-tutorial.asciidoc#L132)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

ESR 45
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/876)*

**Comment by Artur-** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/876)*

**Pull request merged**
