### PR TITLE
Add migration guide for testbench 5

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/845)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[doc/releasenotes.html, line 550 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf56Q1Hd1zNdVCtBSL:-KXf56Q1Hd1zNdVCtBSM:bvbw4j7) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/doc/releasenotes.html#L550)):*
> ```HTML
>         <li><tt>RadioButtonGroupElement</tt> added to test <tt>RadioButtonGroup</tt> Component</li>
>         <li>Elements for compatibility Components were deprecated</li>
>         <li><tt>getCommandExecutor</tt> was removed from <tt>TestBenchElement</tt>, use <tt>getTestBenchCommandExecutor</tt> instead</li>
> ```

Was this done the right or the wrong way around? Looking at this it seems that we should rather have removed `getTestBenchCommandExecutor` and left `getCommandExecutor` 

---

*[documentation/testbench-migration.asciidoc, line 11 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf5uRq1kv3VRbtwmsg:-KXf5uRq1kv3VRbtwmsh:b-fmiiej) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/documentation/testbench-migration.asciidoc#L11)):*
> ```AsciiDoc
> 
> [[testbench.migration.introduction]]
> == Introduction
> ```

"Can I run tests on my FW8 app without upgrading from TB4?"

---

*[documentation/testbench-migration.asciidoc, line 12 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf5vNwzrUBLk1d6Fge:-KXf5vNxhKaUhGZlsDA6:b-3rktm9) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/documentation/testbench-migration.asciidoc#L12)):*
> ```AsciiDoc
> [[testbench.migration.introduction]]
> == Introduction
> ```

"Can I upgrade to TB5 in my FW7 app?"

---

*[documentation/testbench-migration.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf68ehRFfCID1NsVYR:-KXf68ehRFfCID1NsVYS:br7k5uz) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/documentation/testbench-migration.asciidoc#L21)):*
> ```AsciiDoc
> * [classname]#CheckBoxGroupElement# added to test [classname]#CheckBoxGroup# Component
> * [classname]#RadioButtonGroupElement# added to test [classname]#RadioButtonGroup# Component
> * [classname]#Elements# for compatibility Components were deprecated
> ```

"How should I take the deprecation into account?" 
"I am using TableElement, what should I migrate to?"

---

*[documentation/testbench-migration.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf6H1bYhqAzpxoHvz1:-KXf6H1bYhqAzpxoHvz2:b-y88uk5) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/documentation/testbench-migration.asciidoc#L22)):*
> ```AsciiDoc
> * [classname]#RadioButtonGroupElement# added to test [classname]#RadioButtonGroup# Component
> * [classname]#Elements# for compatibility Components were deprecated
> * Method [methodname]#getCommandExecutor# was removed from [classname]#TestBenchElement#, its usages should be replaced with the method [methodname]#getTestBenchCommandExecutor()#
> ```

"What if I have a test cluster?"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/845)*

**Comment by alvarezguille** [comment]
*[doc/releasenotes.html, line 550 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf56Q1Hd1zNdVCtBSL:-KXfAsUL3FyHcT3TGx9T:b-51ikvp) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/doc/releasenotes.html#L550)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Was this done the right or the wrong way around? Looking at this it seems that we should rather have removed `getTestBenchCommandExecutor` and left `getCommandExecutor` 
</blockquote></details>

I'll remove this from this PR and create a separate PR for discussion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/845)*

**Comment by alvarezguille** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/testbench-migration.asciidoc, line 11 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf5uRq1kv3VRbtwmsg:-KXfGWkf5wfCqw0bcOsG:bh7h167) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/documentation/testbench-migration.asciidoc#L11)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

"Can I run tests on my FW8 app without upgrading from TB4?"
</blockquote></details>

check new intro

---

*[documentation/testbench-migration.asciidoc, line 12 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf5vNwzrUBLk1d6Fge:-KXfGY_c8ash7Aix0mvY:bh7h167) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/documentation/testbench-migration.asciidoc#L12)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

"Can I upgrade to TB5 in my FW7 app?"
</blockquote></details>

check new intro

---

*[documentation/testbench-migration.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf68ehRFfCID1NsVYR:-KXfGOL7blWk-S2FbeKC:b-w6x44g) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/documentation/testbench-migration.asciidoc#L21)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

"How should I take the deprecation into account?" 
"I am using TableElement, what should I migrate to?"
</blockquote></details>

added new section

---

*[documentation/testbench-migration.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf6H1bYhqAzpxoHvz1:-KXfGQbWgoi_wv6Y7ZHJ:b32wjw) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/documentation/testbench-migration.asciidoc#L22)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

"What if I have a test cluster?"
</blockquote></details>

dk

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/845)*

**Comment by Artur-** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/testbench-migration.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf6H1bYhqAzpxoHvz1:-KXfJyNA2J1cp6qJY3aH:bugf6ps) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/documentation/testbench-migration.asciidoc#L22)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

dk
</blockquote></details>

Could say just that it "Should work with older (Selenium 2 / TestBench 4 basd) test clusters

---

*[documentation/testbench-migration.asciidoc, line 29 at r2](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXfJtyxyH-jLXTs_SfV:-KXfJtyxyH-jLXTs_SfW:boe8787) ([raw file](https://github.com/vaadin/testbench/blob/8a1c3d49d10ba24b538aff2ea88f086deaf89fbc/documentation/testbench-migration.asciidoc#L29)):*
> ```AsciiDoc
> 
> Vaadin Framework 8 allows adding a compatibility dependency to facilitate the migration between versions 7 and 8 and maintain compatibility for some Components such as Table, Tree, TreeTable, etc.
> ```

Mention e.g. `NativeSelect` and that `NativeSelectElement` can be used also for compatibility classes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/845)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/testbench-migration.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXf6H1bYhqAzpxoHvz1:-KXfRjgFPVRRWAUiLdNZ:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/83190d330dd118a6b1a6147c25118404d191f6f5/documentation/testbench-migration.asciidoc#L22)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Could say just that it "Should work with older (Selenium 2 / TestBench 4 basd) test clusters
</blockquote></details>

Done.

---

*[documentation/testbench-migration.asciidoc, line 29 at r2](https://reviewable.io:443/reviews/vaadin/testbench/845#-KXfJtyxyH-jLXTs_SfV:-KXfRl6Xfol-qax_ZCAY:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/8a1c3d49d10ba24b538aff2ea88f086deaf89fbc/documentation/testbench-migration.asciidoc#L29)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Mention e.g. `NativeSelect` and that `NativeSelectElement` can be used also for compatibility classes
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/845)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/845)*

**Pull request merged**
