### PR TITLE
simplify the base class for own TB6 integration tests

### PR DESCRIPTION
**Pull request by vlukashov**
- merge the 3 base classes into one: MultiBrowserTest + PrivateTB3Configuration + AbstractTB3Test -> AbstractTB6Test
 - remove unused methods

depends on #965

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/966)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 9 of 11 files at r1, 1 of 1 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java, line 19 at r2](https://reviewable.io:443/reviews/vaadin/testbench/966#-L3lZYhq3Voiq2y_Cpax:-L3lZYhq3Voiq2y_Cpay:b-j5mlsh) ([raw file](https://github.com/vaadin/testbench/blob/bdf86a19a54ffb2e4903285352c02362b3f3e2bc/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java#L19)):*
> import java.util.*;

remove star from imports

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java, line 167 at r2](https://reviewable.io:443/reviews/vaadin/testbench/966#-L3lYslK1RH8Tnce7CXO:-L3lYslK1RH8Tnce7CXP:b-hi2wmw) ([raw file](https://github.com/vaadin/testbench/blob/bdf86a19a54ffb2e4903285352c02362b3f3e2bc/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java#L167)):*
>     protected int getDeploymentPort() {
>         return 8080;
>     }

I'm wondering if we should keep the property alternative, same for host name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/966)*

**Comment by Artur-** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java, line 19 at r2](https://reviewable.io:443/reviews/vaadin/testbench/966#-L3lZYhq3Voiq2y_Cpax:-L40Di2iNsERZRl6QPhJ:b-886gsx) ([raw file](https://github.com/vaadin/testbench/blob/bdf86a19a54ffb2e4903285352c02362b3f3e2bc/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java#L19)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> import java.util.*;

remove star from imports
</blockquote></details>

Fixed

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java, line 167 at r2](https://reviewable.io:443/reviews/vaadin/testbench/966#-L3lYslK1RH8Tnce7CXO:-L40DqSoJ6YbkgKFwdHz:bpxjjxi) ([raw file](https://github.com/vaadin/testbench/blob/bdf86a19a54ffb2e4903285352c02362b3f3e2bc/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java#L167)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>     protected int getDeploymentPort() {
>         return 8080;
>     }

I'm wondering if we should keep the property alternative, same for host name
</blockquote></details>

Added `local.propertties` and deployment port + hostname property support

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/966)*

**Comment by alvarezguille** [comment]
*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java, line 190 at r4](https://reviewable.io:443/reviews/vaadin/testbench/966#-L4p0fBCfE9deUTJUm_D:-L4p0fBCfE9deUTJUm_E:bl60bgt) ([raw file](https://github.com/vaadin/testbench/blob/b0a54330c02c8a1722cba58dd73e2e98bea36464/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java#L190)):*
> ```Java
> 
>     protected String getDeploymentHostname() {
>         String hostName = "";
> ```

Should this be initialized as "localhost"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/966)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/966)*

**Comment by Artur-** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java, line 190 at r4](https://reviewable.io:443/reviews/vaadin/testbench/966#-L4p0fBCfE9deUTJUm_D:-L4p698FW3OLBBdRfZbf:b2nhswy) ([raw file](https://github.com/vaadin/testbench/blob/b0a54330c02c8a1722cba58dd73e2e98bea36464/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java#L190)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

Should this be initialized as "localhost"?
</blockquote></details>

Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/966)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r5.
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/966)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/966)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/966)*

**Pull request merged**
