### PR TITLE
feat!: change wrap naming

### LINKED ISSUE #1488: Change Wrap to Tester and wrap(component) to test(component)

### PR DESCRIPTION
**Pull request by caalador**
Change Wrap to Tester and
the wrap method to test.
Also change Wraps annotation to Tests

fixes #1488

### CODE REVIEW

**Comment by mcollovati** [comment]
Should we rename also `@ComponentWrapPackages` to `@ComponentTesterPackages`?

**Comment by mcollovati** [comment]
We should maybe rename also test classes (eg `RadioButtonGroupWrapTest` -> `RadioButtonGroupTesterTest`) but this can also be done in a separate PR.
Also some javadocs may be updated to use the term `tester` instead of `wrapper`, but again we can do it in another PR.

**Comment by caalador** [comment]
Some javaDocs might still have the wrong naming. 
Some have been left at  `test wrapper` as it is not for the name, but for the usage.

**Comment by caalador** [comment]
Thanks, way too many files changing all around the project

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
