### PR TITLE
Click on buttons using space in IE

### PR DESCRIPTION
**Pull request by Artur-**
This should resolve most problems with IE misclicking and not
hitting buttons at all

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/853)

### CODE REVIEW

**Comment by rogozinds** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 195 at r1](https://reviewable.io:443/reviews/vaadin/testbench/853#-KYmBicGJFzZYlH8QP0m:-KYmBicGJFzZYlH8QP0n:b-qjg931) ([raw file](https://github.com/vaadin/testbench/blob/19e5493bea239b6305f8640e83422f80be5546cc/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L195)):*
> ```Java
>         if (BrowserUtil.isIE(getCapabilities())) {
>             // IE randomly misclicks because of problems in the IE driver.
>             // This is a workaround for Vaadin buttons and native buttons, which
> ```

Why it's not in the ButtonElement class? I guess for support "native" buttons, but that's inconsistent, because other methods doesn't support native buttons.

Another issue is that ButtonElement has a hack for buttons with style hidden and this is a hack for IE, will be nice just to have them in one place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/853)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 195 at r1](https://reviewable.io:443/reviews/vaadin/testbench/853#-KYmBicGJFzZYlH8QP0m:-KYmcX9CLOFy7jpLgJep:b-waadz) ([raw file](https://github.com/vaadin/testbench/blob/19e5493bea239b6305f8640e83422f80be5546cc/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L195)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Why it's not in the ButtonElement class? I guess for support "native" buttons, but that's inconsistent, because other methods doesn't support native buttons.

Another issue is that ButtonElement has a hack for buttons with style hidden and this is a hack for IE, will be nice just to have them in one place.
</blockquote></details>

All WebElements are TestBenchElements unless you specifically wrap them as something else. It would be weird if `click` worked differently depending on how you retrieve the element reference.

The ButtonElement hack should probably then be in this method also, if it should work also if you do something like
`findElement(By.id("mybutton")).click()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/853)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 199 at r1](https://reviewable.io:443/reviews/vaadin/testbench/853#-KYmct-mnIlRvKPXajAc:-KYmct-mnIlRvKPXajAd:b-fh6p58) ([raw file](https://github.com/vaadin/testbench/blob/19e5493bea239b6305f8640e83422f80be5546cc/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L199)):*
> ```Java
>             if (hasClassName("v-button")
>                     || "button".equalsIgnoreCase(getTagName())) {
>                 actualElement.sendKeys(Keys.SPACE);
> ```

For some cases, this could potentially cause problems (e.g. somebody has globally mapped space to a short cut or some other weird thing). There should thus be a way to skip this behavior

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/853)*

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 199 at r1](https://reviewable.io:443/reviews/vaadin/testbench/853#-KYmct-mnIlRvKPXajAc:-KYn6UVAFLBWWaB3USkZ:bwtp71v) ([raw file](https://github.com/vaadin/testbench/blob/19e5493bea239b6305f8640e83422f80be5546cc/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L199)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

For some cases, this could potentially cause problems (e.g. somebody has globally mapped space to a short cut or some other weird thing). There should thus be a way to skip this behavior
</blockquote></details>

Added a system property for this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/853)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/853)*

**Comment by Artur-** [comment]
Let's skip this for now as the Framework project indicates that if you are running with `requireWindowFocus`, then `sendKeys` will not work properly

**Pull request closed without merging**
