### PR TITLE
Add waitUntil helper method for Element and TestCase

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/917)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Next step would be adding an overload without the timeout param, but that would require a good idea for default timeout

**Comment by Artur-** [comment]
AbstractTB3Test used 10 seconds, which sounds reasonable

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/917#-:-Kr6P8Jn7MSx1tOypuXT:bto99yq)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 545 at r2](https://reviewable.io:443/reviews/vaadin/testbench/917#-Kr9vpYwrK5dkfobXlVd:-Kr9vpYwrK5dkfobXlVe:b-ed7c6s) ([raw file](https://github.com/vaadin/testbench/blob/526e5ca6880294cfb4c34cab293034b07e71af69/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L545)):*
> ```Java
>      *            false.
>      * @param timeoutInSeconds
>      *            The timeout in seconds when an expectation is called
> ```

What does this mean? What happens on timeout?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/917)*

**Comment by Artur-** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 577 at r3](https://reviewable.io:443/reviews/vaadin/testbench/917#-KrACZd_mXKrP3gPD9Fr:-KrACZd_mXKrP3gPD9Fs:b-ampbfo) ([raw file](https://github.com/vaadin/testbench/blob/18e4d6a8d2844a7098ffed6542c96050ba7ce25d/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L577)):*
> ```Java
>      * 
>      * @throws TimeoutException
>      *             If the 10 seconds passed.
> ```

remove "the"

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java, line 254 at r3](https://reviewable.io:443/reviews/vaadin/testbench/917#-KrACbKTuCVKvr4IMStT:-KrACbKTuCVKvr4IMStU:b-7wvd38) ([raw file](https://github.com/vaadin/testbench/blob/18e4d6a8d2844a7098ffed6542c96050ba7ce25d/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java#L254)):*
> ```Java
>      * 
>      * @throws TimeoutException
>      *             If the 10 seconds passed.
> ```

Remove "the"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/917)*

**Comment by Artur-** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/917)*

**Comment by alvarezguille** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 577 at r3](https://reviewable.io:443/reviews/vaadin/testbench/917#-KrACZd_mXKrP3gPD9Fr:-KrADCUB90gFuFGtDYgu:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/18e4d6a8d2844a7098ffed6542c96050ba7ce25d/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L577)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

remove "the"
</blockquote></details>

Done.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java, line 254 at r3](https://reviewable.io:443/reviews/vaadin/testbench/917#-KrACbKTuCVKvr4IMStT:-KrADD6XMSg0f3kZrlVe:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/18e4d6a8d2844a7098ffed6542c96050ba7ce25d/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java#L254)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Remove "the"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/917)*

**Comment by Artur-** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/917)*

**Pull request merged**
