### PR TITLE
Make ComboBoxElement.selectByText throw an exception for no match

### PR DESCRIPTION
**Pull request by Artur-**
In most (all) cases you want selectByText to select an option. If no
option is selected, you most typically have a problem with your test
and this should not be hidden.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/835)

### CODE REVIEW

**Comment by rogozinds** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/testbench/835#-KXFqqPiJOLNa76BOVmK:-KXFqqPiJOLNa76BOVmL:b-7v1s7v) ([raw file](https://github.com/vaadin/testbench/blob/f1fefbfbad821b406da31df6f645266737e478e5/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java#L57)):*
>         throw new NoSuchElementException(
>                 "No option with text '" + text + "' found");
This will throw exception every time.
add else around it
else {
  throw exception.
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/835)*

**Comment by rogozinds** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/835)*

**Comment by alvarezguille** [comment]
regarding non existent options and readonly state, shouldn't selectByText behavior be the same for al select elements?

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/835#-:-KXeqv2Gy7zcLNXEcwSE:bnfp4nl)*

**Comment by rogozinds** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/835)*

**Comment by rogozinds** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/835)*

**Comment by alvarezguille** [comment]
do not merge until deciding if consistent behavior is required as part of this or will be done separately 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/835#-:-KYTG9zrHnOZiFxfnZdT:b-4mgs1g)*

**Comment by Artur-** [comment]
This needs to be done in the framework project

**Pull request closed without merging**
