### PR TITLE
Add helper for calling a function on a given element

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/922)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/922#-Kw5LPr_VHfczmzlOKnA:-Kw5LPr_VHfczmzlOKnB:b-xkuliv) (no related file):*
Depends on #920 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/922)*

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 437 at r1](https://reviewable.io:443/reviews/vaadin/testbench/922#-Kw5NWXFExHXfu5tVetB:-Kw5NWXFExHXfu5tVetC:b-onvbsu) ([raw file](https://github.com/vaadin/testbench/blob/cff1c66b2ef068f905781a0bf178bb8588bea82c/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L437)):*
> ```Java
>      *            instance
>      */
>     public static Object wrapElementsInline(Object elementElementsOrValues,
> ```

This name is now wrong as the behavior has changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/922)*

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 437 at r1](https://reviewable.io:443/reviews/vaadin/testbench/922#-Kw5NWXFExHXfu5tVetB:-KwA84kd7XtVtC8lmRKe:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/cff1c66b2ef068f905781a0bf178bb8588bea82c/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L437)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This name is now wrong as the behavior has changed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/922)*

**Comment by vlukashov** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 437 at r1](https://reviewable.io:443/reviews/vaadin/testbench/922#-Kw5NWXFExHXfu5tVetB:-Kw9Tdsf5FosaxVsBEOa:bkf3s3a) ([raw file](https://github.com/vaadin/testbench/blob/cff1c66b2ef068f905781a0bf178bb8588bea82c/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L437)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This method makes sense after looking at the other `wrapXYZ` static methods in this class. But when I just looked at it alone, it was quite difficult to understand what it does and why it could be useful.

This method seems to be tailored for one particular use case - `TestBenchCommandExecutor.executeScript()`. If so, would it make sense to move this method into `TestBenchCommandExecutor` and hide it from the public API?

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 575 at r3](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwAieFnpQw28qPAABAw:-KwAieFoAjJHqOSFV_PC:b-dmti9d) ([raw file](https://github.com/vaadin/testbench/blob/1011970cdd2cabe6e9e9981a0cebda33446da844/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L575)):*
> ```Java
>      */
>     public void scrollIntoView() {
>         getCommandExecutor().executeScript("arguments[0].scrollIntoView()",
> ```

Should this be now rewritten to use the newly added `executeScript` method?
[applies to all other places in this class where some form of `executeScript` is used]

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 788 at r3](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwAghqO28fo50mj33zm:-KwAghqPzfDApWIfY7Em:b-4y2gfq) ([raw file](https://github.com/vaadin/testbench/blob/1011970cdd2cabe6e9e9981a0cebda33446da844/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L788)):*
> ```Java
>      * @see JavascriptExecutor#executeScript(String, Object...)
>      */
>     protected Object executeScript(String script, Object... args) {
> ```

Is this method doing the same thing as `com.vaadin.testbench.TestBenchTestCase#executeScript`? If both methods are necessary, should the difference be explained in the documentation?
[for me it's usually confusing if I find the same method in several places, so I'd like to avoid that whenever possible]

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 791 at r3](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwAmJfIEZUPfdTR2ZRp:-KwAmJfJLnxl1qA0gep3:bmiy1gz) ([raw file](https://github.com/vaadin/testbench/blob/1011970cdd2cabe6e9e9981a0cebda33446da844/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L791)):*
> ```Java
>         WebDriver driver = getDriver();
>         if (driver instanceof JavascriptExecutor) {
>             return ((JavascriptExecutor) getDriver()).executeScript(script,
> ```

Why two different ways to execute JS are used here and in `internalPropertyGet` above?
 - here: `((JavascriptExecutor) getDriver()).executeScript()`
 - in `internalPropertyGet`: `getCommandExecutor().executeScript()`

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java, line 241 at r3](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwAjvaNhcPlIg3cU4yX:-KwAjvaObA94-h7IW4eq:b-l7xo24) ([raw file](https://github.com/vaadin/testbench/blob/1011970cdd2cabe6e9e9981a0cebda33446da844/vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java#L241)):*
> ```Java
> 
>     @Override
>     public Object executeScript(String script, Object... args) {
> ```

Would it be useful to mention in the docs (javadoc) that unlike `org.openqa.selenium.JavascriptExecutor.executeScript` this method converts any returned `WebElement` into a `TestBenchElement`?

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java, line 252 at r3](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwAlHR0v9sHT1h3812C:-KwAlHR0v9sHT1h3812D:b2c57vq) ([raw file](https://github.com/vaadin/testbench/blob/1011970cdd2cabe6e9e9981a0cebda33446da844/vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java#L252)):*
> ```Java
> 
>     @Override
>     public Object executeAsyncScript(String script, Object... args) {
> ```

Should this method perform the same conversion of `WebElement` into `TestBenchElement` as its sync version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/922)*

**Comment by Artur-** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 437 at r1](https://reviewable.io:443/reviews/vaadin/testbench/922#-Kw5NWXFExHXfu5tVetB:-KwEAtZMhTUNEYb7L5dJ:bljukgx) ([raw file](https://github.com/vaadin/testbench/blob/cff1c66b2ef068f905781a0bf178bb8588bea82c/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L437)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

This method makes sense after looking at the other `wrapXYZ` static methods in this class. But when I just looked at it alone, it was quite difficult to understand what it does and why it could be useful.

This method seems to be tailored for one particular use case - `TestBenchCommandExecutor.executeScript()`. If so, would it make sense to move this method into `TestBenchCommandExecutor` and hide it from the public API?
</blockquote></details>

Yeah, it should be internal anyway. Done

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 575 at r3](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwAieFnpQw28qPAABAw:-KwEGgPYOFVwMOl-7M5T:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/1011970cdd2cabe6e9e9981a0cebda33446da844/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L575)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Should this be now rewritten to use the newly added `executeScript` method?
[applies to all other places in this class where some form of `executeScript` is used]
</blockquote></details>

Done.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 788 at r3](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwAghqO28fo50mj33zm:-KwEHWj1QGi_r7GBoZ5o:b-pamjv) ([raw file](https://github.com/vaadin/testbench/blob/1011970cdd2cabe6e9e9981a0cebda33446da844/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L788)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Is this method doing the same thing as `com.vaadin.testbench.TestBenchTestCase#executeScript`? If both methods are necessary, should the difference be explained in the documentation?
[for me it's usually confusing if I find the same method in several places, so I'd like to avoid that whenever possible]
</blockquote></details>

They are exactly the same and exist only so that it is easy to execute JS regardless if you happen to write code in your main test method (`TestBenchTestCase`) or in an element class (`TestBenchElement`)

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 791 at r3](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwAmJfIEZUPfdTR2ZRp:-KwEJA0CuJpZDlpsVZ_X:b-zh87ju) ([raw file](https://github.com/vaadin/testbench/blob/1011970cdd2cabe6e9e9981a0cebda33446da844/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L791)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Why two different ways to execute JS are used here and in `internalPropertyGet` above?
 - here: `((JavascriptExecutor) getDriver()).executeScript()`
 - in `internalPropertyGet`: `getCommandExecutor().executeScript()`
</blockquote></details>

Some legacy, some new. Unified.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java, line 241 at r3](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwAjvaNhcPlIg3cU4yX:-KwEJFizVqgAUYEFM5RP:b-mxf3hh) ([raw file](https://github.com/vaadin/testbench/blob/1011970cdd2cabe6e9e9981a0cebda33446da844/vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java#L241)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Would it be useful to mention in the docs (javadoc) that unlike `org.openqa.selenium.JavascriptExecutor.executeScript` this method converts any returned `WebElement` into a `TestBenchElement`?
</blockquote></details>

Yeah but this method is hidden from the user so it should be in `executeScript` in `TestBenchTestCase` and `TestBenchElement` also. Done

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java, line 252 at r3](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwAlHR0v9sHT1h3812C:-KwELS9O-WzLfiN9Rz1g:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/1011970cdd2cabe6e9e9981a0cebda33446da844/vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java#L252)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Should this method perform the same conversion of `WebElement` into `TestBenchElement` as its sync version?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/922)*

**Comment by vlukashov** [comment]
Reviewed 2 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 205 at r4](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwEUBXA6owIW1MwtILB:-KwEUBXBMStZ1v677Xxu:bojjm1w) ([raw file](https://github.com/vaadin/testbench/blob/cec9ea252ad6bc3477dd146fc853c15c438ece5a/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L205)):*
> ```Java
>     @Override
>     public void scroll(int scrollTop) {
>         executeScript("arguments[0].scrollTop = " + scrollTop, actualElement);
> ```

Should this be `setProperty('scrollTop', 0)`?

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 218 at r4](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwEUKS5DOOk4RtWj8PR:-KwEUKS5DOOk4RtWj8PS:bw9lra) ([raw file](https://github.com/vaadin/testbench/blob/cec9ea252ad6bc3477dd146fc853c15c438ece5a/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L218)):*
> ```Java
>     @Override
>     public void scrollLeft(int scrollLeft) {
>         executeScript("arguments[0].scrollLeft = " + scrollLeft, actualElement);
> ```

Should this be `setProperty('scrollLeft', 0)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/922)*

**Comment by Artur-** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 205 at r4](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwEUBXA6owIW1MwtILB:-KwEW02546E7d0i9o2-r:b-9znr2u) ([raw file](https://github.com/vaadin/testbench/blob/cec9ea252ad6bc3477dd146fc853c15c438ece5a/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L205)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Should this be `setProperty('scrollTop', 0)`?
</blockquote></details>

Changed to `setProperty('scrollTop', scrollTop);` although unrelated to this PR

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 218 at r4](https://reviewable.io:443/reviews/vaadin/testbench/922#-KwEUKS5DOOk4RtWj8PR:-KwEW1oTxLJsnE7BGDPG:b8w9pes) ([raw file](https://github.com/vaadin/testbench/blob/cec9ea252ad6bc3477dd146fc853c15c438ece5a/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L218)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Should this be `setProperty('scrollLeft', 0)`?
</blockquote></details>

Changed to `setProperty('scrollLeft', scrollLeft);` although unrelated to this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/922)*

**Comment by vlukashov** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/922)*

**Pull request merged**
