### PR TITLE
Fix issue in *GroupElement when selecting by text in chrome

### PR DESCRIPTION
**Pull request by alvarezguille**
Fixes selectByText for OptionGroupElement, CheckBoxGroupElement and RadioButtonGroupElement

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/837)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2RlwhFX-yZz_r3VD:-KXC2RlwhFX-yZz_r3VE:bdguchb) (no related file):*
Add `Fixes #836`

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2_GWf4XUIOD6ixDM:-KXC2_GXjl3My6zvQ2Zi:b-j38wfq) ([raw file](https://github.com/vaadin/testbench/blob/6533709c13a38e990b32cef41ab2eb3d3bb11ae7/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java#L52)):*
> ```Java
>                     // When using Valo, the input element is covered by a
>                     // pseudo-element, which Firefox will complain about
>                     getTestBenchCommandExecutor().executeScript(
> ```

Does it make sense to have different workarounds? Looks like the Firefox one would work with Chrome also, or even with all supported browers?

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2iffmEhDQ_LOx9zs:-KXC2iffmEhDQ_LOx9zt:bxpjzc1) ([raw file](https://github.com/vaadin/testbench/blob/6533709c13a38e990b32cef41ab2eb3d3bb11ae7/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java#L59)):*
> ```Java
>                     input.click();
>                 }
>             }
> ```

Is this the same code as in CheckBoxElement? Maybe create a helper as it might (probably will be) needed somewhere else also?

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2rZfpFzArAnDS5_3:-KXC2rZfpFzArAnDS5_4:b-3p181b) ([raw file](https://github.com/vaadin/testbench/blob/6533709c13a38e990b32cef41ab2eb3d3bb11ae7/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java#L50)):*
> ```Java
>             if (text.equals(option.findElement(byLabel).getText())) {
>                 WebElement input = option.findElement(byRadioInput);
>                 if (isFirefox()) {
> ```

I think I have seen this code before somewhere

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/RadioButtonGroupElement.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2u35rVbVEGAKsSeC:-KXC2u35rVbVEGAKsSeD:brxg8fb) ([raw file](https://github.com/vaadin/testbench/blob/6533709c13a38e990b32cef41ab2eb3d3bb11ae7/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/RadioButtonGroupElement.java#L49)):*
> ```Java
>             if (text.equals(option.findElement(byLabel).getText())) {
>                 WebElement input = option.findElement(byRadioInput);
>                 if (isFirefox()) {
> ```

This code looks familiar

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/837)*

**Comment by alvarezguille** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2RlwhFX-yZz_r3VD:-KXF-nER22OYVe-PZ79z:bb7f2mf) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Add `Fixes #836`
</details>
done

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2_GWf4XUIOD6ixDM:-KXF-qqEb2L0cbgdwUQN:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/6533709c13a38e990b32cef41ab2eb3d3bb11ae7/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java#L52)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Does it make sense to have different workarounds? Looks like the Firefox one would work with Chrome also, or even with all supported browers?
</details>
Done.

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2iffmEhDQ_LOx9zs:-KXF-y30JbPTXvphlZu-:b3t0wqr) ([raw file](https://github.com/vaadin/testbench/blob/6533709c13a38e990b32cef41ab2eb3d3bb11ae7/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java#L59)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Is this the same code as in CheckBoxElement? Maybe create a helper as it might (probably will be) needed somewhere else also?
</details>
used firefox solution for all browsers

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2rZfpFzArAnDS5_3:-KXF-s3L1AMlWhDfNgAi:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/6533709c13a38e990b32cef41ab2eb3d3bb11ae7/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java#L50)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> I think I have seen this code before somewhere
</details>
Done.

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/RadioButtonGroupElement.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2u35rVbVEGAKsSeC:-KXF-tLFKL3y1JXCkqn_:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/6533709c13a38e990b32cef41ab2eb3d3bb11ae7/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/RadioButtonGroupElement.java#L49)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> This code looks familiar
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/837)*

**Comment by Artur-** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2rZfpFzArAnDS5_3:-KXF393QQA9H00Uer3oa:bnskr80) ([raw file](https://github.com/vaadin/testbench/blob/6533709c13a38e990b32cef41ab2eb3d3bb11ae7/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java#L50)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> Done.
</details>
Could still be moved to `TestBenchElement` as `clickEvenIfHidden` or `forceClick`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/837)*

**Comment by alvarezguille** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/testbench/837#-KXC2rZfpFzArAnDS5_3:-KXFEmJpPwhihLg2cU_c:b4z672r) ([raw file](https://github.com/vaadin/testbench/blob/6533709c13a38e990b32cef41ab2eb3d3bb11ae7/vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java#L50)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Could still be moved to `TestBenchElement` as `clickEvenIfHidden` or `forceClick`
</details>
Changed to clickHiddenElement in TestBenchElement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/837)*

**Comment by Artur-** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/837)*

**Pull request merged**
