### PR TITLE
Avoid an infinite loop when trying to find the innermost driver (#937)

### LINKED ISSUE #945: Infinite loop with TestBench 4.2.0 and Selenium 3.6.0 when using WebDriverWait
Hello folks,

I know the Selenium 3.6.0 is not yet oficially supported, but I'm already using it with TestBench 4.2.0 and there is no significant problem excepting the following one: **when WebDriverWait is used and timeout exception happened Selenium will hang up in an infitine loop**.

**There is one very important change in Selenium. It tries to iterate through the chain of wrapped drivers.**
Check the modification here: https://github.com/SeleniumHQ/selenium/commit/2494e69275c3e82b63f8413a506856ac200954ec

**The problem is the TestBenchDriverProxy implements the getWrappedDriver() method in a very strange way and returns itself (return this;).** Bang and infinite loop is here!

Can you fix it please as soon as possible?
Thanx and best regards!

### PR DESCRIPTION
**Pull request by alvarezguille**
Fixes #945

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/949)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/949)*

**Comment by qwikso** [comment]
Hi @Artur-, @alvarezguille 
we are still waiting for a new 4.* release including this fix. Could you build it please?
Thank you.
Regards Roman.

**Comment by johannesh2** [comment]
Good point. Thanks for reminding. I'll put this to next sprint.

**Comment by johannesh2** [comment]
And sorry for totally forgetting this.

**Comment by qwikso** [comment]
No problem:) If I want to get a notification when new version is released, where should I subscribe? Thanks.

**Comment by oluwasayo** [comment]
Released as 4.2.1 https://github.com/vaadin/testbench/releases/tag/4.2.1

**Pull request merged**
