### PR TITLE
 Rewrite ElementQuery to use querySelectorAll and look inside the shadow root of elements

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/923)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/923#-Kw5M4WgaXslDanAmmRd:-Kw5M4WgaXslDanAmmRe:b-xkulh5) (no related file):*
Depends on #922 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/923)*

**Comment by Artur-** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 830 at r1](https://reviewable.io:443/reviews/vaadin/testbench/923#-Kw5PKiH4LpCqPc3uDZV:-Kw5PKiH4LpCqPc3uDZW:bkwwcqb) ([raw file](https://github.com/vaadin/testbench/blob/7531ba23a4a711948bf85d32e7f9a681809a3217/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L830)):*
> ```Java
>      *             If no matching elements are found
>      */
>     public TestBenchElement getShadowElementById(String id) {
> ```

This should be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/923)*

**Comment by vlukashov** [comment]
Reviewed 7 of 13 files at r1, 1 of 4 files at r2, 2 of 4 files at r3.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/923)*

**Comment by vlukashov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/923)*

**Pull request merged**
