### PR TITLE
make ElementQuery search both in the light DOM and inside the shadow root

### PR DESCRIPTION
**Pull request by vlukashov**
add a polymer-based test view
add a test verifying TestBenchElement.$() finds slotted content
make ElementQuery search both in the light DOM and inside the shadow root

Depends on #925

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/932)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/932#-Kwdk9is3m4sBKNPS6Cq:-Kwdk9is3m4sBKNPS6Cr:b-ffj8b9) (no related file):*
Why is a production build needed for integration tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/932)*

**Comment by vlukashov** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench/932#-Kwdk9is3m4sBKNPS6Cq:-KwdqkdrLJgil7P5cjxF:b-bgmzqr) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why is a production build needed for integration tests?
</blockquote></details>

Indeed, it's not needed. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/932)*

**Comment by Artur-** [comment]
Reviewed 8 of 12 files at r2, 4 of 6 files at r4.
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/PolymerTemplateView.java, line 13 at r4](https://reviewable.io:443/reviews/vaadin/testbench/932#-KweA09bvrIRpbShD5ge:-KweA09cnkAeIDckQKly:btsm6ah) ([raw file](https://github.com/vaadin/testbench/blob/a6a4f9eed96b54876e087cb65b0ad5d43247f528/vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/PolymerTemplateView.java#L13)):*
> ```Java
> @Route("PolymerTemplateView")
> @Tag("polymer-template-view")
> @HtmlImport("context://src/polymer-template-view.html")
> ```

`context://` can be removed

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java, line 23 at r3](https://reviewable.io:443/reviews/vaadin/testbench/932#-KwdkIhThfxzrupXrpRz:-KwdkIhThfxzrupXrpS-:byhn71x) ([raw file](https://github.com/vaadin/testbench/blob/d62ba3ceac91a930c40215cc12be99e1b68f2cf0/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java#L23)):*
> ```Java
>         openTestURL();
> 
>         PolymerTemplateViewElement view = $(PolymerTemplateViewElement.class).waitForFirst();
> ```

Is `waitForFirst` really needed here? Would indicate that `waitForVaadin` is broken

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/PolymerTemplateViewElement.java, line 7 at r4](https://reviewable.io:443/reviews/vaadin/testbench/932#-KweFg585pK3ckbZ-vvt:-KweFg585pK3ckbZ-vvu:bk06lfp) ([raw file](https://github.com/vaadin/testbench/blob/a6a4f9eed96b54876e087cb65b0ad5d43247f528/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/PolymerTemplateViewElement.java#L7)):*
> ```Java
> 
> @Element("polymer-template-view")
> public  class PolymerTemplateViewElement extends TestBenchElement {
> ```

What's with the double space? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/932)*

**Comment by Artur-** [comment]
Reviewed 1 of 6 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/932)*

**Comment by Artur-** [comment]
Reviewed 1 of 6 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/932)*

**Comment by vlukashov** [comment]
Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/PolymerTemplateView.java, line 13 at r4](https://reviewable.io:443/reviews/vaadin/testbench/932#-KweA09bvrIRpbShD5ge:-KweHzTPcJjxRRxNSXFA:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/a6a4f9eed96b54876e087cb65b0ad5d43247f528/vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/PolymerTemplateView.java#L13)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

`context://` can be removed
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java, line 23 at r3](https://reviewable.io:443/reviews/vaadin/testbench/932#-KwdkIhThfxzrupXrpRz:-KweI29gGQVyLot9QXDA:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/d62ba3ceac91a930c40215cc12be99e1b68f2cf0/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java#L23)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Is `waitForFirst` really needed here? Would indicate that `waitForVaadin` is broken
</blockquote></details>

Done.

---

*[vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/PolymerTemplateViewElement.java, line 7 at r4](https://reviewable.io:443/reviews/vaadin/testbench/932#-KweFg585pK3ckbZ-vvt:-KweI6lB2v6Uqmd6YLcD:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/a6a4f9eed96b54876e087cb65b0ad5d43247f528/vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/PolymerTemplateViewElement.java#L7)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

What's with the double space? :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/932)*

**Comment by Artur-** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/932)*

**Pull request merged**
