### PR TITLE
Fix visibility of TestBenchElement methods and remove extra methods

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/814)

### CODE REVIEW

**Comment by Artur-** [comment]
For 5.0

**Comment by alvarezguille** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 356 at r1](https://reviewable.io:443/reviews/vaadin/testbench/814#-KW7kqnbGhmdAnt6EnlE:-KW7kqnbGhmdAnt6EnlF:bfruyxv) ([raw file](https://github.com/vaadin/testbench/blob/461afad568d00bd96db906717a38d71735443eb1/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L356)):*
> ```Java
>     @Override
>     public TestBenchCommandExecutor getTestBenchCommandExecutor() {
>         return getTestBenchCommandExecutor();
> ```

StackOverflowError

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/814)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 356 at r1](https://reviewable.io:443/reviews/vaadin/testbench/814#-KW7kqnbGhmdAnt6EnlE:-KWgVJ4Efb3HYPV3BBes:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/461afad568d00bd96db906717a38d71735443eb1/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L356)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> StackOverflowError
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/814)*

**Comment by alvarezguille** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 383 at r2](https://reviewable.io:443/reviews/vaadin/testbench/814#-KWnA_hHMaJ1ag5qbF1Q:-KWnA_hHMaJ1ag5qbF1R:bgi46wf) ([raw file](https://github.com/vaadin/testbench/blob/63d0e72075a161cf10d7a1f677b3e91b7b428aae/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L383)):*
>     public TestBenchCommandExecutor getCommandExecutor() {
>         return tbCommandExecutor;
>     }
Existing calls to  getCommandExecutor in ElementAPI should be replaced with getTestBenchCommandExecutor() check build results

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/814)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/814)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java, line 383 at r2](https://reviewable.io:443/reviews/vaadin/testbench/814#-KWnA_hHMaJ1ag5qbF1Q:-KWrHBKLB3GUvkC9mJmO:b-896fix) ([raw file](https://github.com/vaadin/testbench/blob/63d0e72075a161cf10d7a1f677b3e91b7b428aae/vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java#L383)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> >     public TestBenchCommandExecutor getCommandExecutor() {
> >         return tbCommandExecutor;
> >     }
> Existing calls to  getCommandExecutor in ElementAPI should be replaced with getTestBenchCommandExecutor() check build results
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/814)*

**Pull request merged**
