### PR TITLE
Make it possible to selectByText in ComboBoxes with text input disabled

### LINKED ISSUE #758: ComboBoxElement selectByText does not work correctly
**Originally by _rhaex_**

___
When using a ComboBoxElement to control the behaviour of a ComboBox during integration tests, the value selecting does not work correctly when the ComboBox has setTextInputAllowed set to false.

It uses javascript to remove the read only flag, type in the selection and then re enable the read only flag. This changes the value in the ComboBox but does not trigger a value change event, and when you continue the value returns to the original value.

___
 Imported from https://dev.vaadin.com/ issue #15316

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #758

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench/829)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/combobox/ComboBoxInputNotAllowedIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/testbench/829#-KX56uD7qUOkxScvvPwJ:-KX56uD8EE6pke8EO8IA:b-soap0d) ([raw file](https://github.com/vaadin/testbench/blob/3c05bc8b695c8ed360f801a4294f3830b16a5d92/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/combobox/ComboBoxInputNotAllowedIT.java#L18)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>     @Test
>     public void selectByTextComboBoxWithTextInputDisabled_invalidSelection() {
>         openTestURL();
>         ComboBoxElement cb = $(ComboBoxElement.class).first();
>         cb.selectByText("Foobar");
>     }
</details>
what is this supposed to test? what's the expected outcome? no exception is thrown?

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/combobox/ComboBoxUIIT.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/testbench/829#-KX5An_9mEw6zAlufveu:-KX5An_9mEw6zAlufvev:bs9aca4) ([raw file](https://github.com/vaadin/testbench/blob/3c05bc8b695c8ed360f801a4294f3830b16a5d92/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/combobox/ComboBoxUIIT.java#L56)):*
> ```Java
>         ComboBoxElement cb = $(ComboBoxElement.class).first();
>         cb.selectByText("foobar");
>     }
> ```


same as with ComboBoxInputNotAllowedIT

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/829)*

**Comment by Artur-** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/combobox/ComboBoxInputNotAllowedIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/testbench/829#-KX56uD7qUOkxScvvPwJ:-KX5CIgmyJXgrciQenC8:bleobwr) ([raw file](https://github.com/vaadin/testbench/blob/3c05bc8b695c8ed360f801a4294f3830b16a5d92/testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/combobox/ComboBoxInputNotAllowedIT.java#L18)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> >     @Test
> >     public void selectByTextComboBoxWithTextInputDisabled_invalidSelection() {
> >         openTestURL();
> >         ComboBoxElement cb = $(ComboBoxElement.class).first();
> >         cb.selectByText("Foobar");
> >     }
> what is this supposed to test? what's the expected outcome? no exception is thrown?
</details>
Right now it's a bit stupid as it only tests that no exception is thrown. The initial patch version threw an exception when the option is not found but I noted this was inconsistent with how `selectByText` currently works. I planned on making a separate patch to change both `selectByText` versions to throw if the option is not found, but this would go into TB5 then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/829)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench/829)*

**Comment by alvarezguille** [comment]
@Artur- remember release notes
also, are you pushing same change to master?

**Pull request merged**
